// Assay — a decoder for Swift that tells you what went wrong.
// Copyright 2026 Srinivas Iyer. Licensed under the Apache License, Version 2.0.
// See LICENSE and NOTICE at the repository root for terms.

// GENERATED by gen-decode-widths.sh — do not edit. CI diffs this file against the
// generator's output.
//
// The narrow integer widths, one primitive family each. `Int8`, `Int16`, `UInt8`,
// `UInt16`, `UInt32` and `UInt64` are field types on every path; `UInt64` inherits
// `UInt`'s ceiling at `Int64.max` because `scanInt64` is the carrier (Decode.swift).

extension AssayReader {

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeInt8(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString, _ element: Int = -1
    ) -> Int8? {
        beginValue()
        if let v = scanInt64(), let n = Int8(exactly: v) { return n }
        failed(&sink, path, key, "integer", element)
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeInt8OrNull(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> Int8?? {
        beginValue()
        if scanNull() { return .some(nil) }
        if let v = scanInt64(), let n = Int8(exactly: v) { return .some(n) }
        failed(&sink, path, key, "integer")
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeInt8Coercing(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> Int8? {
        guard let v = _decodeIntCoercing(&sink, path, key) else { return nil }
        guard let n = Int8(exactly: v) else {
            overflowed(&sink, path, key, v)
            return nil
        }
        return n
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeInt16(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString, _ element: Int = -1
    ) -> Int16? {
        beginValue()
        if let v = scanInt64(), let n = Int16(exactly: v) { return n }
        failed(&sink, path, key, "integer", element)
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeInt16OrNull(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> Int16?? {
        beginValue()
        if scanNull() { return .some(nil) }
        if let v = scanInt64(), let n = Int16(exactly: v) { return .some(n) }
        failed(&sink, path, key, "integer")
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeInt16Coercing(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> Int16? {
        guard let v = _decodeIntCoercing(&sink, path, key) else { return nil }
        guard let n = Int16(exactly: v) else {
            overflowed(&sink, path, key, v)
            return nil
        }
        return n
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt8(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString, _ element: Int = -1
    ) -> UInt8? {
        beginValue()
        if let v = scanInt64(), let n = UInt8(exactly: v) { return n }
        failed(&sink, path, key, "integer", element)
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt8OrNull(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> UInt8?? {
        beginValue()
        if scanNull() { return .some(nil) }
        if let v = scanInt64(), let n = UInt8(exactly: v) { return .some(n) }
        failed(&sink, path, key, "integer")
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt8Coercing(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> UInt8? {
        guard let v = _decodeIntCoercing(&sink, path, key) else { return nil }
        guard let n = UInt8(exactly: v) else {
            overflowed(&sink, path, key, v)
            return nil
        }
        return n
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt16(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString, _ element: Int = -1
    ) -> UInt16? {
        beginValue()
        if let v = scanInt64(), let n = UInt16(exactly: v) { return n }
        failed(&sink, path, key, "integer", element)
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt16OrNull(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> UInt16?? {
        beginValue()
        if scanNull() { return .some(nil) }
        if let v = scanInt64(), let n = UInt16(exactly: v) { return .some(n) }
        failed(&sink, path, key, "integer")
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt16Coercing(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> UInt16? {
        guard let v = _decodeIntCoercing(&sink, path, key) else { return nil }
        guard let n = UInt16(exactly: v) else {
            overflowed(&sink, path, key, v)
            return nil
        }
        return n
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt32(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString, _ element: Int = -1
    ) -> UInt32? {
        beginValue()
        if let v = scanInt64(), let n = UInt32(exactly: v) { return n }
        failed(&sink, path, key, "integer", element)
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt32OrNull(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> UInt32?? {
        beginValue()
        if scanNull() { return .some(nil) }
        if let v = scanInt64(), let n = UInt32(exactly: v) { return .some(n) }
        failed(&sink, path, key, "integer")
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt32Coercing(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> UInt32? {
        guard let v = _decodeIntCoercing(&sink, path, key) else { return nil }
        guard let n = UInt32(exactly: v) else {
            overflowed(&sink, path, key, v)
            return nil
        }
        return n
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt64(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString, _ element: Int = -1
    ) -> UInt64? {
        beginValue()
        if let v = scanInt64(), let n = UInt64(exactly: v) { return n }
        failed(&sink, path, key, "integer", element)
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt64OrNull(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> UInt64?? {
        beginValue()
        if scanNull() { return .some(nil) }
        if let v = scanInt64(), let n = UInt64(exactly: v) { return .some(n) }
        failed(&sink, path, key, "integer")
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decodeUInt64Coercing(
        _ sink: inout IssueSink, _ path: [PathStep], _ key: StaticString
    ) -> UInt64? {
        guard let v = _decodeIntCoercing(&sink, path, key) else { return nil }
        guard let n = UInt64(exactly: v) else {
            overflowed(&sink, path, key, v)
            return nil
        }
        return n
    }
}
