#!/bin/bash
# Assay — a decoder for Swift that tells you what went wrong.
# Copyright 2026 Srinivas Iyer. Licensed under the Apache License, Version 2.0.
# See LICENSE and NOTICE at the repository root for terms.

# Generates DecodeWidths.swift: the three decode primitives for each narrow integer width.
#
#     ./gen-decode-widths.sh > DecodeWidths.swift
#
# Eighteen functions that differ in one type name. They were hand-copied until 2026-09-10,
# which is how a family of three grows a fourth spelling nobody notices; CI regenerates
# this file and fails if the checked-in copy differs. The reason they are eighteen
# functions and not one generic is in Decode.swift's header: monomorphic per type, no
# `FixedWidthInteger` dispatch at the leaf.
set -euo pipefail

cat <<'EOF'
// Assay — a decoder for Swift that tells you what went wrong.
// Copyright 2026 Srinivas Iyer. Licensed under the Apache License, Version 2.0.
// See LICENSE and NOTICE at the repository root for terms.

// GENERATED by gen-decode-widths.sh — do not edit. CI diffs this file against the
// generator's output.
//
// The narrow integer widths, one primitive family each. `Int8`, `Int16`, `UInt8`,
// `UInt16`, `UInt32` and `UInt64` are field types on every path; `UInt64` inherits
// `UInt`'s ceiling at `Int64.max` because `scanInt64` is the carrier (Decode.swift).

extension AssayReader {
EOF

for T in Int8 Int16 UInt8 UInt16 UInt32 UInt64; do
cat <<EOF

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decode${T}(
        _ sink: inout IssueSink, _ path: [PathComponent], _ key: StaticString
        , _ element: Int = -1
    ) -> ${T}? {
        beginValue()
        if let v = scanInt64(), let n = ${T}(exactly: v) { return n }
        failed(&sink, path, key, "integer", element)
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decode${T}OrNull(
        _ sink: inout IssueSink, _ path: [PathComponent], _ key: StaticString
    ) -> ${T}?? {
        beginValue()
        if scanNull() { return .some(nil) }
        if let v = scanInt64(), let n = ${T}(exactly: v) { return .some(n) }
        failed(&sink, path, key, "integer")
        return nil
    }

    @_documentation(visibility: internal)
    @inlinable
    public mutating func _decode${T}Coercing(
        _ sink: inout IssueSink, _ path: [PathComponent], _ key: StaticString
    ) -> ${T}? {
        guard let v = _decodeIntCoercing(&sink, path, key) else { return nil }
        guard let n = ${T}(exactly: v) else {
            overflowed(&sink, path, key, v)
            return nil
        }
        return n
    }
EOF
done

echo "}"
