# Current numbers

**One machine, one run: macOS 26.5.2, Apple silicon (arm64), Apple Swift 6.3.3, `-O`, warm,
minimum of 5 rounds — 2026-09-13, commit `1487e38`.** None of these is a claim about
another platform (`CLAUDE.md`'s honesty rules); Linux and x86-64 have their own sections
below. Each row links to the journal entry that explains what it measures and what it does
not. Regenerate with `swift run -c release AssayBench` and replace this table — the numbers
are machine-specific by design, so this is pasted, not automated.

**The struct rows moved on 2026-09-13** and the reason is one line of the emitter: the
generated body built a diagnostic path per array element, for a path read only when the
document is malformed. Total allocations at fifty items went 257 → **159**, so this is less
work rather than more memory — see [the efficiency audit](#doing-less-not-spending-more).

| arm | number | against | journal |
|---|---|---|---|
| struct decode, full corpus | **9.79×** mean over 25 files (5.64–18.62) | `JSONDecoder` | [three passes](#three-passes-because-one-number-cannot-answer-three-questions) |
| prefix decode + unknown-key skip | **6.12×** over 45 files | `JSONDecoder` | same |
| generic value model | **3.06×** over 75 files | `JSONSerialization` | same |
| falsification arm (`apimodel`, 5 sizes) | **5.84×** mean (8.36× float-dense) | `JSONDecoder` | [Phase 1](#phase-1--the-falsification-check) |
| vs ZippyJSON (simdjson + Codable) | **3.58×** faster | ZippyJSON, which is 2.08× over Foundation here | [the owed number](#the-owed-loss-assay-against-yyjson) |
| vs yyjson, use-case shape | **0.73×** (loses) | yyjson parse + extraction | same |
| vs yyjson, float-dense | **0.73×** (loses) | same | same |
| vs yyjson, DOM vs DOM | **0.13×** (loses) | `yyjson_read` | same |
| YAML node parse | **6.56×** | Yams `compose` | [YAML and XML](#yaml-and-xml-timed-for-the-first-time) |
| YAML struct decode | **11.09×** | Yams `YAMLDecoder` | same |
| XML tree parse | **2.33×** (macOS; **0.96×** on Linux) | Foundation `XMLParser` | [XML, made faster](#making-the-xml-parser-faster-by-profiling-rather-than-by-admiring-libxml2) |
| TOML node parse | **1.51×** | toml++ via TOMLKit | [TOML](#toml-a-fourth-tree-decoder-against-c) |
| TOML struct decode | **2.41×** | TOMLKit `TOMLDecoder` | same |
| `Date` fields | **8.04×** | `JSONDecoder` + `.iso8601` | [Dates](#dates-the-unclaimed-win-claimed) |
| binary plist | **~5.7×** | Foundation `PropertyListDecoder` | [coverage](#the-arms-that-did-not-exist) |
| XML plist | **~1.4×** | Foundation `PropertyListDecoder` | same |
| union vs its variant | **1.17×** (the tag scan) | the variant decoded directly | same |
| `@Inline` vs nesting | **0.82×** (faster) | the nested `@Schema` it replaces | same |
| `@Wraps` vs `@Validate` | **2.03×** (slower) | the plain field + rule it is sugar for | same |
| encoding, 50 / 200 items | **2.98× / 2.80×** | `JSONEncoder` | `docs/ENCODING.md` |
| cold start, 60 types | **7.8×** first decode (median); 6.4× steady | `JSONDecoder` | `ColdStartBench.swift` |
| multi-megabyte documents | **10.0–10.3×**, ~1,050 MB/s, flat | `JSONDecoder` | `LargeDocBench.swift` |
| total allocations, 50 items | **159** against Foundation's 378 | `JSONDecoder` | [doing less](#doing-less-not-spending-more) |
| `T.validate(_:)` | **72 ns** per value, 1 block; **82 ns/row** batched, 0.17× a decode | — | [Validating a value](#validating-a-value-you-already-have) |
| live allocations, `apimodel-8k` struct | gated, **PASS** | absolute thresholds | [Allocations](#allocations) |
| compile time, 10 fields | **79.4 ms/type** (gate 100) | `Codable`: 4.75× | `docs/COMPILE-TIME.md` |

---

# Phase 1 — the falsification check

**Status: PASSED, decisively. The thesis holds.**

- Toolchain: Apple Swift 6.3.3, `arm64-apple-macosx26.0`, macOS 26.5.2, Apple silicon
- Build: `swift build -c release` (`-O`). **Not** `-Ounchecked`.
- Corpus: `Benchmarks/Corpus/files/apimodel-*.json`, generated by `Sources/CorpusGen`, seed 20260726
- Date: 2026-07-26

## The condition being tested

`docs/PERFORMANCE.md` §14, phase 1:

> Benchmark against Foundation on the corpus of §12.2 and count allocations. **If this
> does not comfortably clear ZippyJSON's 1.38×, the thesis is wrong and everything below
> is moot.**

ZippyJSON attached simdjson — the fastest JSON parser in existence — to Swift's
`Decodable` and measured **1.38× average over Foundation, 1.04×** on the most API-shaped
payload in its own set. Assay's claim is that the parser was never the bottleneck, so a
*scalar* decoder that deletes the container boundary should clear that comfortably.

## Result

### `apimodel` — mixed API payload

| size | bytes | Foundation ns/op | Assay ns/op | ratio |
|---|---|---|---|---|
| 512b | 851 | 5,712 | 930 | **6.14×** |
| 2k | 2,256 | 13,478 | 2,403 | **5.61×** |
| 8k | 8,270 | 45,699 | 8,407 | **5.44×** |
| 32k | 33,043 | 180,908 | 34,191 | **5.29×** |
| 64k | 65,740 | 360,409 | 69,462 | **5.19×** |

**Mean: 5.53× over Foundation.** Scalar Swift. No SIMD, no C, no arena.

### `floats-dense` — canada.json-shaped, and the prediction was wrong

| size | bytes | Foundation ns/op | Assay ns/op | ratio |
|---|---|---|---|---|
| 512b | 525 | 15,235 | 1,688 | **9.03×** |
| 2k | 2,053 | 57,964 | 6,453 | **8.98×** |
| 8k | 8,196 | 228,989 | 26,687 | **8.58×** |
| 32k | 32,772 | 917,986 | 108,338 | **8.47×** |
| 64k | 65,542 | 1,846,296 | 216,640 | **8.52×** |

**Mean: 8.72×** — the *largest* margin in the suite, on the shape this document previously
listed as an expected loss.

The earlier claim ("a decoder with no SIMD number parsing will lose there") conflated two
different baselines. Against **simdjson or yyjson**, which carry Eisel-Lemire, a scalar
decoder plausibly does lose on float-dense input — that remains untested and unclaimed.
Against **Foundation** it does not, because Foundation calls `strtod_clocale` per value
(`JSONScanner.swift:1184`) — a locale-aware C function reached through a buffer — while
Assay's Clinger fast path is a multiply against an exactly-representable power of ten on
bytes already in L1.

Every float is asserted **bit-identical** to Foundation's before timing.

## Why this is the number the thesis predicted

Two independent measurements bracket it:

- ZippyJSON: simdjson + `Decodable` → **1.38×**. Faster parser, same container boundary.
- Apple's `new-codable` prototype: same parser, no container boundary → **~6×**.

Assay lands at **5.20×**, next to Apple's number rather than ZippyJSON's. That is the
decomposition the whole design rests on — roughly five sixths of a Swift decode is
structural overhead and roughly one sixth is looking at bytes — arriving as a measurement
rather than an argument.

The ratio *declining* with size (5.82× → 4.89×) is also the predicted shape: fixed
per-call overhead is a larger share of Foundation's cost at small sizes, and Assay has
less of it. The 1–50 kB band is where the advantage is largest, which is exactly the band
the published literature excludes.

## Fairness, stated rather than buried

- Foundation's `JSONDecoder` is fully general and `Codable`-driven; Assay's macro knows
  the schema at compile time. **That is a real advantage and an unfair comparison unless
  said out loud.** Saying it out loud.
- The `Codable` model declares snake_case field names *directly* rather than using
  `.convertFromSnakeCase`. That is deliberately favourable to Foundation — the key
  strategy would have added a String allocation and transform per key.
- Both decoders are hoisted out of the loop (**warm**). Real servers decode the same type
  thousands of times, so warm is the honest default — but it flatters any decoder that
  amortizes setup. A cold-start arm is still owed.
- Assay receives `[UInt8]`; Foundation receives `Data`, its native input. Neither pays a
  conversion inside the timed region.
- Minimum of 5 rounds, not a mean. Correctness is asserted against Foundation's own output
  before timing — a fast wrong answer is not a result.

## What was NOT measured at this run

> **Update, 2026-07-27.** Items 1 and 4 below have since been addressed; see
> "The full corpus, and the allocation gate" at the end of this file. Items 2, 3, 5 and 6
> stand open and are tracked in `ROADMAP.md`.

1. **Allocations per decode.** This is the *headline* claim in `PERFORMANCE.md` §12.5 —
   "the minimum number of heap allocations a Swift decoder can perform" — and it is the
   metric CI is supposed to gate on, because it is deterministic and machine-independent
   where wall clock is not. Getting it needs `ordo-one/package-benchmark`'s malloc
   interposer; `malloc_zone_statistics` exposes live blocks, not a total count, so there
   is no shortcut. **No allocation claim may be made until this exists.**
2. **Cold start.** The axis where a macro emitting no `CodingKeys` and no `Decodable`
   witness should win structurally, and which no steady-state benchmark can see.
3. **Linux and x86-64.** Everything here is one arm64 machine.
4. **The other corpus shapes.** Only `apimodel` is measured; `escaped`, `unknown-keys`,
   `optionals-absent` and the six negative cases are generated but unmeasured.
5. **The classic corpus against a SIMD baseline.** `floats-dense` above shows Assay beating
   *Foundation* on float-dense input. It says nothing about simdjson, yyjson, or
   sonic-rs, all of which carry Eisel-Lemire. That comparison is still owed, and it is the
   one where a loss is genuinely expected.
6. **Dictionary-typed fields.** `[String: T]` is not implemented at all yet, so the case
   `PERFORMANCE.md` §2.5 calls Assay's worst is entirely unmeasured. The structural
   expectation is a *narrowed* margin rather than a loss: Assay must build the user's
   dictionary, one allocation plus a hash and a `String` per key, but Foundation builds
   **two** — its internal `[String: JSONMap.Value]` per object *and* the user's.
   *(Update 2026-08-07: implemented and measured — see "Dictionaries: the stated worst
   case, measured" at the end of this file. 6.95× mean; the narrowing is real, the
   loss is not.)*

## What changed since the first run

Two measured improvements, both traceable to a specific line in the research:

1. **Clinger fast path for `Double`** (`Numbers.swift`). Previously every double
   round-tripped through a `String` to reach the stdlib parser — exactly what
   `perf-dispatch-and-hot-path.md` §2.6 says not to do, since the stdlib's own 20% claim
   for its pure-Swift rewrite was attributed almost entirely to removing that copy. Now:
   significand ≤ 2^53 and |exponent| ≤ 22 → one multiply or divide against an
   exactly-representable power of ten, which is *correctly rounded* by Clinger's result,
   not approximately. Everything else falls back to the stdlib.
   Main arm 5.21× → 5.53×; float-dense 8.72×.
   Verified by 4,000+ generated decimals compared **bit-for-bit** against `Double(String)`,
   plus the subnormal, 2^53+1, and 1-ulp edge cases (`Tests/AssayTests/DoubleTests.swift`).

2. **Recursive array decoding**, so `[[Double]]` works at all.

## Reproduce

```sh
cd Benchmarks && swift run -c release CorpusGen
cd Benchmarks && swift run -c release AssayBench
```

---

# The full corpus, and the allocation gate

**2026-07-27.** The run above measured two shapes out of a corpus of 81 files, and made no
allocation claim because none could be measured. Both are now addressed.

## Three passes, because one number cannot answer three questions

| pass | what it decodes | mean vs Foundation | files |
|---|---|---|---|
| Struct decode | shapes a fixed struct consumes entirely | **9.17×** | 25 |
| Prefix + unknown-key skip | flat shapes, 6-field struct, rest skipped | **6.43×** | 45 |
| Generic value model | `JSON.Value` vs `JSONSerialization` | **1.49×** | 75 |

The prefix pass exists because the flat corpus shapes scale by **adding keys** —
`bigints-64k` has 2,232 of them — so a fixed struct necessarily decodes a prefix and skips
the remainder. That is not a defect in the measurement; it is the single most common real
shape there is, a client struct against a verbose server response, and both decoders do the
same work.

The generic-value pass is the honest floor. A value model has no `Codable` boundary to
delete, so **1.49× is what Assay's scanner is worth on its own**, separate from everything
the macro contributes. Anyone reading 9.17× should read that row next to it.

## The negative path

| file | Foundation ns | Assay ns | issues found |
|---|---|---|---|
| `neg-invalid-early` | 646 | 183 | 1 |
| `neg-invalid-late` | 19,707 | 3,724 | 6 |
| `neg-truncated` | 5,558 | 1,663 | 1 |
| `neg-type-mismatch` | 21,025 | 3,602 | 6 |
| `neg-validation-fail-many` | 19,622 | 3,609 | 6 |
| `neg-deep-nesting` | 8,724 | 529 | 3 |

Foundation throws on the first problem and stops. Assay walks the entire document and
reports every one — and is still faster doing it. A slower number here would have been the
feature working, not a regression; it did not come to that.

## Allocations

`.mallocCountTotal` was rejected, not deferred: package-benchmark's malloc metrics need
jemalloc installed beside the toolchain, and cannot run on the musl or wasm legs of the
matrix at all. What is gated instead is **live blocks per decoded value**, via
`malloc_zone_statistics`.

| case | Assay blocks | Assay bytes | Foundation blocks | Foundation bytes |
|---|---|---|---|---|
| `apimodel-8k` struct | 118.7 | 15,072 | 118.7 | 15,072 |
| `apimodel-8k` value model | 142.6 | 28,862 | 173.9 | 14,388 |
| `arrays-of-scalars-8k` | 2.0 | 10,272 | 1.8 | 10,265 |
| `short-strings-8k` | 1.0 | 112 | 0.9 | 106 |

Three limitations, stated where the code is rather than buried:

1. **Not total malloc traffic.** Transient allocations made and freed inside a decode never
   appear.
2. **Undercounts ~10–15% on Darwin.** A self-check measures closures whose block count is
   arithmetic and reads 1.70 where the answer is 2 — the nano zone reports batched
   statistics. Thresholds carry the headroom, and the gate disables itself if the error
   grows rather than reporting a number it cannot stand behind.
3. **Cannot compare two decoders that retain the same data.** `Payload` and
   `CodablePayload` hold identical `String`s and `Array`s, so they hold identical blocks —
   which is why the `apimodel-8k` struct row reads the same on both sides. The measurement
   is correct and the comparison is vacuous. **The Foundation columns are context, never a
   claim.**

What survives all three is the question actually worth gating on, and on it the answer is
unambiguous:

- `arrays-of-scalars-8k` decodes ~800 integers into **2 blocks** — the retaining box and
  one exactly-sized `[Int]`. No doubling sequence, no per-element boxing.
- `short-strings-8k` decodes six string fields into **1 block** — the box alone. Every one
  of those `String`s is ≤ 15 bytes, so small-form and immortal, and allocates nothing.

Those are `PERFORMANCE.md` §13.2's design claims arriving as measurements. A `Dictionary`
appearing in the per-object path would show up here immediately, which is the regression
the gate exists to catch.

## Correctness, alongside speed

- **Differential:** `JSON.Value` agrees with `JSONSerialization` value-for-value on all 75
  positive corpus files.
- **Fuzz:** 9,680 deterministic byte mutations and truncations per run through all three
  parsers — no crash, no hang. It found a real YAML flow-collection hang (`[}]` looped
  forever appending empty scalars until the OOM killer) inside its first 466 inputs.

Both run in CI.

## Reproduce

```sh
cd Benchmarks
swift run -c release CorpusGen
swift run -c release AssayBench     # falsification arm, full sweep, allocation gate
swift run -c release DiffFuzz       # differential + fuzz
```

---

# YAML and XML, timed for the first time

**2026-08-05.** Same machine, same toolchain, same rules as above (warm, minimum of 5
rounds, `-O`). Until this run every published Assay number was JSON, and the honest
sentence was "the YAML and XML parsers are verified correct against independent
implementations, and nothing whatsoever is known about their speed."

**The JSON thesis does not transfer, and these numbers must not be read through it.**
The 5–9× JSON ratios come from deleting the `Codable` container boundary at compile
time. The YAML and XML paths build a node tree and decode structs from `RawValue` — a
tree walk, not a fused decode — so there is no boundary being deleted and no
architectural reason to expect JSON-sized margins. These rows exist to catch pathologies
and to place Assay against what a Swift project would otherwise use.

The corpus is the `apimodel` ladder re-rendered as block-style YAML and as XML by
`Sources/CorpusRender` — **the same bytes DiffFuzz verifies against libyaml and
Foundation in the same CI** before this harness ever times them. Every row is gated on
both sides producing the same shape.

## YAML node parse — `YAML.parse` vs `Yams.compose`

Tree vs tree; neither side resolves scalars. Yams crosses into libyaml (C).

| size | bytes | Yams ns/op | Assay ns/op | ratio |
|---|---|---|---|---|
| 512b | 978 | 21,700 | 3,273 | **6.63×** |
| 2k | 2,631 | 54,517 | 8,220 | **6.63×** |
| 8k | 9,696 | 196,355 | 29,553 | **6.64×** |
| 32k | 38,928 | 795,396 | 120,371 | **6.61×** |
| 64k | 77,504 | 1,591,464 | 241,108 | **6.60×** |

**Mean: 6.62×.** The flatness across sizes says this is throughput, not fixed-overhead
amortisation. libyaml itself is fast C; what Yams pays is the crossing — every scalar
comes back through the C event API and materialises as a Swift `String` before a `Node`
exists. Assay parses the bytes directly into its node model and skips the toll booth.

## YAML struct decode — `T.parse(yaml:)` vs Yams' `YAMLDecoder` (Codable)

The comparison a migrating project would actually make.

| size | bytes | YAMLDecoder ns/op | Assay ns/op | ratio |
|---|---|---|---|---|
| 512b | 978 | 54,862 | 4,851 | **11.31×** |
| 2k | 2,631 | 136,807 | 12,191 | **11.22×** |
| 8k | 9,696 | 479,897 | 41,650 | **11.52×** |
| 32k | 38,928 | 1,909,266 | 168,521 | **11.33×** |
| 64k | 77,504 | 3,817,720 | 335,067 | **11.39×** |

**Mean: 11.36×** — larger than any JSON ratio, and for a reason the JSON section already
established: `YAMLDecoder` pays the compose cost above *and then* the `Codable` container
boundary on top. It is the two measured costs stacked, arriving stacked.

## XML tree parse — `XML.parse` vs Foundation `XMLParser` (counting delegate)

| size | bytes | Foundation ns/op | Assay ns/op | ratio |
|---|---|---|---|---|
| 512b | 1,084 | 9,626 | 6,266 | **1.54×** |
| 2k | 2,829 | 20,759 | 15,617 | **1.33×** |
| 8k | 10,285 | 68,891 | 55,988 | **1.23×** |
| 32k | 41,173 | 272,657 | 226,388 | **1.20×** |
| 64k | 81,934 | 541,397 | 445,622 | **1.21×** |

**Mean: 1.30×, and the comparison is asymmetric in Foundation's favour**, stated rather
than buried: Assay builds and keeps the whole tree — attributes, namespace resolution,
source structure — while the Foundation side only counts events and sums text bytes,
strictly less work than any consumer that keeps the document. A parser instance per
iteration is Foundation's own requirement, not a handicap added here.
`shouldProcessNamespaces` is left off (cheaper for Foundation; the rendered corpus has no
namespaces). Read it as "Assay's full tree costs less than Foundation's events alone",
not as a 1.3× parser claim.

There is no XML struct-decode row because Foundation has no Codable XML decoder to
compare against; a comparison against third-party XMLCoder would need a new dependency
and is not owed to any thesis.

## What was NOT measured here

- **Linux, x86-64, cold start** — same as every number in this file: one arm64 Mac, warm.
- **Scalar resolution** — both YAML rows leave scalars unresolved on both sides by
  design; a workload that resolves everything immediately pays costs not measured here.
- **Flow-style YAML, anchors at volume, deep nesting** — the rendered corpus is
  block-style and anchor-free. The differential covers those shapes for correctness;
  nothing times them.
- **Allocation counts** for either format. The gate is JSON-only.

## Reproduce

```sh
cd Benchmarks
swift run -c release CorpusGen
swift run -c release AssayBench     # the YAML/XML tables print after the JSON summary
```

---

# Dates: the unclaimed win, claimed

**2026-08-06.** `PERFORMANCE.md` §13.2 named a hand-written ISO-8601 parser as an
unclaimed win and the `uuids-and-dates` corpus shape had been waiting for it since the
generator was built. `Date` and `@DateFormat` are now implemented (ROADMAP.md §2,
unblocked by putting Hinnant's days-from-civil arithmetic in the core and letting the
macro emit `Date(timeIntervalSince1970:)` into the user's module).

## `@Schema [Date]` vs Foundation `JSONDecoder` + `.iso8601` strategy

Documents built from every date string in the `uuids-and-dates` corpus files, so the
byte distribution is the corpus's. Every epoch is asserted **bit-identical** to
Foundation's before timing.

| size | dates | Foundation ns/op | Assay ns/op | ratio |
|---|---|---|---|---|
| 512b | 8 | 5,284 | 905 | **5.84×** |
| 2k | 25 | 15,158 | 2,568 | **5.90×** |
| 8k | 92 | 52,562 | 8,638 | **6.09×** |
| 32k | 341 | 192,171 | 30,854 | **6.23×** |
| 64k | 688 | 384,857 | 61,810 | **6.23×** |

**Mean: 6.06×.** Both sides parse the same JSON around the dates, so this understates
the difference in the date path itself: Assay's is two dozen integer operations
(Hinnant's algorithm), Foundation's `.iso8601` strategy goes through
`ISO8601DateFormatter`. The ratio *rising* with size — opposite to the apimodel table —
is the same effect from the other side: more dates per document means the date path is
a larger share of the work.

## Correctness, before any of it was timed

- **2,279 instants agree with Foundation exactly** (Double equality, no tolerance) in
  DiffFuzz's date differential: a prime-stepped sweep of ±68 years formatted by
  Foundation and reparsed, 1,000 pseudo-random civil dates parsed by both, and the
  IMF-fixdate sweep against a POSIX-locale `DateFormatter`.
- Deliberate divergences are pinned as such, in both directions:
  - Assay **accepts** `:60` leap seconds (real logs contain them; POSIX carry into the
    next minute). Foundation rejects them.
  - Foundation **accepts** `2026-02-29`, `2026-04-31` and hour `24` — and silently
    *rolls them over* to Mar 1, May 1, and the next midnight. Assay rejects all three
    with the field named. A validating decoder that quietly moves a date to a
    different day would be the exact bug class this library exists to refuse; the
    differential fails if Foundation ever becomes strict, so the divergence cannot rot
    into an accident.

---

# Dictionaries: the stated worst case, measured

**2026-08-07.** `[String: T]` fields are implemented (JSON and RawValue paths, recursive
— `[String: [Int]]`, `[[String: Int]]`, `[String: [String: Int]]` all nest; non-String
keys are a purpose-written macro diagnostic). `PERFORMANCE.md` §2.5 called this the
structural worst case while it did not exist; now it exists and is measured. Corpus
objects re-wrapped as `{"m": <object>}`, entry-for-entry equality with Foundation gated
before timing.

| shape | size | Foundation ns/op | Assay ns/op | ratio |
|---|---|---|---|---|
| bigints | 512b | 13,597 | 1,561 | **8.71×** |
| bigints | 8k | 166,162 | 23,291 | **7.13×** |
| bigints | 64k | 1,301,628 | 233,560 | **5.57×** |
| short-strings | 512b | 19,064 | 2,635 | **7.23×** |
| short-strings | 8k | 236,882 | 33,352 | **7.10×** |
| short-strings | 64k | 1,822,375 | 304,775 | **5.98×** |

**Mean: 6.95× over 10 rows** (full table in the harness output). The prediction was a
*narrowed margin*, and the narrowing is real — the ratio declines from 8.7× toward 5.6×
as the user's `Dictionary` (a hash and a `String` per key, the cost the struct path
deletes) grows as a share of the work. What the prediction undercounted is Foundation's
side of the same ledger: it builds its internal `JSONMap`, then the user's dictionary,
*and* crosses the `Codable` boundary per entry. Assay pays only the user's map. The
worst case is a 5.6–8.7× win, and §2.5's caution can be retired with numbers rather
than argument.

---

# Where decode time actually goes — the gate on phases 4 and 5

**2026-08-08.** `docs/PERFORMANCE.md` §14 makes SIMD (phase 4) and C (phase 5)
conditional on numbers. This is the number they are conditional on, and it was never
measured: Amdahl applied honestly, because the most a vectorised UTF-8 validator can win
is the share of decode time that validator occupies.

| shape | size | decode ns | validate ns | validate share | `JSON.Value` scan share |
|---|---|---|---|---|---|
| apimodel | 8k | 9,329 | 492 | **5.3%** | 304% |
| apimodel | 64k | 77,149 | 3,829 | **5.0%** | 299% |
| short-strings | 8k | 3,938 | 485 | **12.3%** | 778% |
| short-strings | 64k | 30,372 | 3,817 | **12.6%** | 786% |
| long-strings | 8k | 3,664 | 489 | **13.4%** | 314% |
| long-strings | 64k | 28,112 | 3,814 | **13.6%** | 347% |
| floats-dense | 8k | 29,086 | 486 | **1.7%** | 446% |
| floats-dense | 64k | 232,530 | 1,928 | **0.8%** | 450% |

**UTF-8 validation is 8.1% of decode on average and 13.6% at its worst.** So a *perfect*
vectorised validator — zero cost, not merely faster — improves end-to-end decode by at
most 13.6% on the friendliest shape and about **5% on the API-shaped payload the
falsification condition used**. A realistic 4× validator wins ~10% and ~4% respectively.

That is phase 4's headline win, bounded by measurement instead of estimated. It does not
say SIMD is worthless — it says SIMD is worth single digits on the path that is the
product, and the decision to spend that effort should be made with the number visible.

The right-hand column is the same architecture claim arriving from the other direction:
building a `JSON.Value` tree costs **3–8× what decoding straight into a struct costs**,
over the identical bytes and the identical scanner. Deleting the boundary is where the
performance is; the boundary was never the parser.

## A hypothesis that was wrong, published because it was wrong

Reading the generated code suggested a real cost: every nested object and every array
element evaluates `path + [.key(...)]`, allocating a fresh array **on the success path**,
and the allocation gate cannot see it — those allocations are freed during the decode,
which is documented limitation #1 of the live-block counter.

Measured by removing the concatenation from the macro and re-running the corpus, the
difference was **inside run-to-run noise** on every nested shape (`arrays-of-structs`,
`nested-3-deep`, `mixed`). The allocation is real; its cost is not detectable against the
string construction it sits next to. The hack was reverted. Recorded here so nobody
"optimises" it later on the strength of the same plausible reasoning.

## Leak and race verification

- `leaks --atExit` over both harnesses: **0 leaks, 0 leaked bytes** — including the
  benchmark run's 157 million allocations, which exercises `MappedFile`'s `munmap`
  `deinit` and the class-backed `AssayError` storage.
- AddressSanitizer and ThreadSanitizer: clean over the full suite.
- 400 concurrent decodes across JSON/YAML/XML plus both renderers, and 300 concurrent
  date parses over the shared tables: clean under ThreadSanitizer.

---

# The owed loss: Assay against yyjson

**2026-08-08.** Every ratio published before this one was against Foundation.
`docs/PERFORMANCE.md` has said from the beginning that a comparison against a SIMD-tier C
parser was owed, and that the float-dense arm is where a scalar Swift decoder with no
Eisel-Lemire *should lose*. Here it is. Assay loses all three arms, by between 1.3× and
16×, and the numbers are published because they were predicted.

Baseline: **yyjson** (MIT, `ibireme/yyjson`), vendored into the benchmark package only —
never the library — and built the way its own benchmarks build it: `-O3`, non-standard
extensions off, default read flags. It is hand-tuned C with a bespoke float parser, and
on DOM parsing it trades places with simdjson.

*This is yyjson, not simdjson.* simdjson is C++ and would need an interop shim; the claim
here is "a SIMD-tier C parser", and it should not be read as a simdjson number.

## Fairness, arranged against Assay on purpose

- yyjson's document is **freed inside the timed region**, because Assay's ARC teardown is
  inside its own.
- **Not** yyjson's in-situ mode, which is faster but mutates the input buffer. Assay does
  not mutate its input, so in-situ would not be the same promise — but it means the
  baseline is running with one hand behind its back, and a reader should know that.
- The use-case arm makes yyjson build **real Swift `String`s and `Array`s**, because that
  is the cost Assay pays and hiding it would flatter Assay. Note this cuts slightly the
  other way too: `String(cString:)` re-validates UTF-8 that yyjson already checked, a cost
  Assay's whole-buffer validation lets it skip.
- Every value is asserted **equal, recursively, key for key in document order** before
  anything is timed — which makes this a third independent differential as well as a
  benchmark. The corpus already agreed with `JSONSerialization`; it now agrees with
  hand-tuned C.

## DOM vs DOM — `JSON.Value.parse` vs `yyjson_read`

| shape | size | yyjson ns | Assay ns | ratio | (was, before 2026-09-11) |
|---|---|---|---|---|---|
| apimodel | 8k | 1,600 | 13,174 | **0.12×** | 0.05× |
| apimodel | 64k | 14,326 | 105,120 | **0.14×** | 0.06× |
| floats-dense | 64k | 46,890 | 394,542 | **0.12×** | 0.05× |
| short-strings | 64k | 20,281 | 102,916 | **0.20×** | 0.09× |
| arrays-of-structs | 64k | 20,428 | 171,462 | **0.12×** | 0.05× |

**Mean 0.13× — yyjson is roughly 7× faster.** Still not close, and still the honest
scanner-against-scanner number.

### It was 16× until somebody asked whether yyjson had anything to teach

It did, though not the lesson expected. Profiling `JSON.Value.parse` rather than reasoning
about it found `scanJSONArray` and `scanJSONObject` building `path + [.index(…)]` and
`path + [.key(…)]` — **an array allocation per VALUE in the document**, copying the parent
path into it, for a path nothing reads unless the document is malformed. Threading one
array `inout` and pushing/popping around each descent took the DOM path **2.1–2.6× faster**
and the corpus-wide value-model sweep from 1.51× to 3.11× over `JSONSerialization`.

That is the third time this exact mistake has been found in this codebase — the columnar
row path (2026-09-10), haul's report before it, and now here. It is worth naming as a
pattern rather than three incidents: **a diagnostic path threaded eagerly through a hot
loop is invisible in every test, because tests assert on the diagnostics rather than on
what producing them cost.** The `colfloor` arm exists for the columnar one; this section is
the record for this one.

### What the remaining 7× is, and what closing it would cost

Profiled again after the fix, and it is now what the original write-up predicted: string
materialisation. `scanString` plus `makeString` plus `String.init(unsafeUninitializedCapacity:)`
plus the memmove under them is the top of the profile, and `makeString` is already the
cheapest way to build one Swift `String` from bytes.

yyjson does not build strings at all. It writes a tape into one arena and its string values
point into the input buffer. Assay's `JSON.Value` is a Swift enum tree: every string an
individually ARC-managed `String`, every container an `Array`. Closing that gap means a
different public type — a document that owns a tape, with a cursor type reading it — and
CLAUDE.md's `~Escapable` note already records why that is a second API rather than a change
to this one.

So the conclusion is unchanged and now better supported: **`JSON.Value` is not the fast path
and should never be presented as one.** It exists so `@Extras` and "I do not know this
shape" have somewhere to land. What did change is that the gap is 7× rather than 16×, and
2.1× of that came from deleting work nobody had measured.

## Use case — `@Schema` decode vs yyjson parse *plus extraction*

A DOM you must then walk is not a decoded value. This arm makes yyjson do the whole job.

| size | yyjson ns | Assay ns | ratio |
|---|---|---|---|
| 512b | 623 | 1,014 | **0.61×** |
| 2k | 1,584 | 2,616 | **0.61×** |
| 8k | 5,731 | 9,073 | **0.63×** |
| 32k | 25,414 | 36,873 | **0.69×** |
| 64k | 52,020 | 74,142 | **0.70×** |

**Mean 0.65× — hand-tuned C is about 1.5× faster.** That is the number to put next to
"5.53× Foundation", and both are true: Assay sits between Foundation and C, closer to C
than to Foundation, and it is *behind* C.

## float-dense — the arm that was predicted to lose

| size | yyjson ns | Assay ns | ratio |
|---|---|---|---|
| 512b | 1,359 | 1,810 | **0.75×** |
| 8k | 22,356 | 28,738 | **0.78×** |
| 64k | 183,062 | 230,157 | **0.80×** |

**Mean 0.78× — yyjson is 1.28× faster**, and the gap *narrows* as documents grow.

The prediction was right and the margin is smaller than feared. `PERFORMANCE.md` §6
declined to hand-roll Eisel-Lemire on the grounds that the bounded Clinger fast path
covers essentially all real numeric JSON and that reimplementing Eisel-Lemire for single
digits of improvement was not phase-1 work. At 1.28× behind a parser that *does* carry a
bespoke float algorithm, that call holds up: the remaining gap on the most float-dense
shape in the corpus is smaller than the gap on ordinary API payloads.

## What this changes

- The honesty rules already forbade claiming "fastest JSON decoder". This is the
  measurement that makes that restraint concrete rather than modest.
- **The 5–9× Foundation numbers are unaffected and remain the relevant comparison for the
  audience**, which is Swift programs currently using `Codable`. Nobody migrating from
  `JSONDecoder` gets yyjson's number without also writing the extraction by hand and
  giving up typed errors, source spans, validation and every format but JSON.
- It closes `ROADMAP.md`'s "SIMD decoder comparison" verification gap, and it re-frames
  phase 4: the earlier decomposition bounded a vectorised validator's win at ~5% on this
  shape, and this arm shows the true gap to C is ~1.5×. Vectorising validation does not
  close it. Whatever does, it is not that.

---

# The third decode path, measured — and withdrawn on its own numbers

**2026-08-09, closed 2026-08-10.** `docs/KEYED-SOURCE.md` justified a general row-at-a-time
`KeyedSource` protocol with a claim: reaching already-parsed data through the `RawValue` path
"costs an allocation per value per record." That was reasoning, not measurement, and it was
false — `RawValue.mapping` is one allocation per record.

The measurements below are what closed the design. **The row path was removed; the columnar
half survives.** The tables are kept because a design that was measured and dropped is more
useful written down than forgotten, and because the numbers are the whole argument.

## Narrow row — 8 columns, all 8 declared

| approach | ns/record | live blocks |
|---|---|---|
| KeyedSource, byte-compared keys | 119 | 1.0 |
| build `RawValue`, then decode | **93** | 1.0 |
| `DictionarySource` (hashes per lookup) | 209 | 1.0 |

Once the row protocol's presence semantics were corrected — four states, not two — the same
comparison read **311 ns against 95**. It lost to the path it was invented to beat, by 3.3×,
on the shape most rows have.

It also could not accept the borrowed rows it existed for (a zero-copy row view is
`~Escapable`, which this library refuses in its public surface), and its cost landed **per
row** in a driver generic over the schema, at 1.6–4.7×. Three independent reasons, any one
of which would have been enough.

## What replaced it

`T.validate(_:)` — a specialised reader decodes at its own speed in its own module, and Assay
runs the rules afterwards. Measured below under "Validating a value you already have", and
documented in `docs/VALIDATE.md`.

---

## Columnar batch fill

**2026-08-09.** The loop inverted: pull each column once, sequentially, instead of touching
all eight column arrays per record. Same column store on both sides, and the row-wise
source reads *straight out of the columns* — no per-row array is built — so the only thing
separating the two is the access pattern.

| rows | row-by-row | batch | ns/row | batch wins |
|---|---|---|---|---|
| 64 | 6,407 ns | 3,277 ns | 51 | 1.96× |
| 1,000 | 106,180 ns | 52,082 ns | 52 | 2.04× |
| 20,000 | 2,113,742 ns | 1,043,996 ns | 52 | 2.02× |
| 100,000 | 10,767,375 ns | 5,205,854 ns | 52 | **2.07×** |

**A flat 2×, and flat is the interesting part.** The per-row cost is 52 ns at 64 rows and 52
ns at 100,000 — a 1,500× range — so this is not a cache-residency effect that appears once
the data outgrows L2. It is the access pattern itself: eight strided reads per record
against one sequential pass per column, and the ratio holds wherever the data lives.

That also means the honest claim is narrower than "columnar is cache-friendly". At these
widths the win is *structural*, not *hierarchical* — a wider table or larger per-row payload
would be where residency starts to matter, and that is unmeasured.

### What it cost to keep honest

Two things biased the first version of this comparison and both were removed:

- The row-wise arm **built an `[RawValue]` per record** to feed the source. That is an
  allocation the batch path never makes, so it was measuring array construction rather than
  striding. Replaced with a source that reads the column arrays directly.
- Constructing that source per record **retained eight array references per row**. The
  source is now built once and walked, so the loop measures access and nothing else.

Both changes made the result *smaller* and more defensible. A comparison that flatters the
new thing is worth less than one that survives having its advantages removed.

### Behaviour, which is the actual bar

Identical to every other path, and tested rather than assumed: `@Validate` runs per row with
the **row index in the issue path**, defaults and validity masks give the same five presence
states, and a **missing required column is reported once for the batch** rather than once per
row — a property of the source, not of each record, in the same spirit as
`BoundPlan.missingRequired` failing before the first row is touched.

## The columnar extension point — what a consumer's own scalar costs

**2026-08-30.** `ColumnDecodable` lets a type Assay has never heard of — a `Timestamp`, a
`Decimal128`, a fixed-width identifier — be a field of a `@Schema(sources: true)` type.
The measured question is whether it reintroduces the dispatch cost that killed the row path.

Same store, same column, same two-field schema, 100,000 rows. The only difference is whether
the field is declared `Int64` or a `ColumnDecodable` type carried by `Int64`.

| field type | ns/batch | ns/row |
|---|---|---|
| `Int64`, built in | 4,264,854 | 42.65 |
| `Micros`, `ColumnDecodable` | 4,228,770 | **42.29** |

**0.99×.** Three runs gave 0.99×, 0.99× and 1.02×, so the hook is free and the spread is the
measurement rather than the feature.

> **That conclusion is wrong, and the numbers above are why it took ten days to see.**
> Corrected 2026-09-11 — the hook costs about **3 ns/row, 1.66–2.02×**. Both columns above
> carry a per-row diagnostic-path allocation of ~38 ns that was removed on 2026-09-10; a
> 3 ns difference inside 42 ns is 7%, which is exactly what "the spread is the measurement"
> looks like. The section at the end of this file has the re-measurement and the mechanism.
> The rest of this entry — the shape table below, and why the generic call belongs once per
> column — stands unchanged, and is the part that was actually being argued.

That is not luck, and the shape it avoids was measured first, in isolation, across a real
module boundary, converting one `Int64` per value:

| shape | ns/value |
|---|---|
| baseline — copy `Int64`, no conversion | 0.34 |
| concrete `init`, as the macro emits it | 0.35 |
| through a generic parameter in the library | **21.35** |
| through an existential | 3.74 |
| generic fetch per column + concrete `init` per row | **0.47** |

The 21.35 row is `KeyedSource`'s shape — a call through a generic parameter inside Assay, in
a loop the consumer drives, which `@inlinable` cannot rescue because SE-0193 forbids it on
generated bodies. It is **57× the concrete call**, and in a path whose per-row budget is
~50 ns it is the 1.6–4.7× that path was retired for.

`ColumnDecodable` splits it: the generic call is `Column._assayFetch`, made **once per
column**, so its cost divides by the row count; the per-row call names a concrete type in
the module that declares the schema, exactly as the macro already emits
`Date(timeIntervalSince1970:)`.

### Bytes columns: flat-plus-offsets, and what the alternative would have cost

`BytesColumn` is Arrow's varbinary layout — every row's bytes in one buffer plus an offsets
array — rather than `[[UInt8]]`. Identical arithmetic over identical bytes, at only **16
bytes per row**:

| access | ns/batch | ns/row |
|---|---|---|
| `range(at:)` into the flat buffer | 5,493,146 | 54.93 |
| `bytes(at:)`, one `Array` per row | 8,422,521 | **84.23** |

**1.53×**, or 27–29 ns/row across runs, and it grows with the blob. `[[UInt8]]` would charge
that to every reader whether or not it wanted a copy — and a Parquet or Arrow reader already
*has* the flat buffer and the offsets, because that is how the format stores them.

The analogy with `stringColumn` returning `[String]` does not carry, which is worth stating
because it is the obvious objection: short strings ride in small-string form and never touch
the heap, and a blob never does.

## Where the generic entry point actually costs — and the API conclusion that follows

**2026-08-09.** `docs/KEYED-SOURCE.md` claimed the generic entry point "specialises within a
module and falls back to witness-table dispatch across one, which is precisely the
arrangement a CSV or Postgres driver in another package would hit." That was reasoning.
Measured, it names the **wrong boundary**.

| arrangement | ns/record | cost |
|---|---|---|
| source in the same module | 124 | — |
| **source in another module**, call site beside the schema | 124 | **1.00×** |
| **loop in the driver**, generic over the schema, per row | 68 vs 42 | **1.63×** |
| **loop in the driver**, generic over the schema, **batch** | 50 vs 52 | **0.96×** |

Putting the *source* in another module costs **nothing**. The generated `_assay<S>` lives in
the schema's module and so does the call site, so the compiler sees both concrete types and
specialises. The caveat was wrong about that.

What *does* cost is being **generic over the schema** — `db.query("…", as: User.self)`, which
is the shape every real driver API takes. There `T` is unknown, `_assay` is non-inlinable
(SE-0193 forbids `@inlinable` on a generated body), and the witness-table call happens **per
row**: 1.63×.

**And the batch entry point erases it.** `T._assayBatch(from:)` pays the dispatch once per
*batch* rather than once per record, because the per-row loop lives inside a function that is
concrete in the schema's own module. Generic-over-schema batch decoding is **0.96×** — free,
within noise.

### The conclusion is an API rule, not a footnote

**A driver's public API should be batch-shaped.** `fetchAll(as: User.self) -> [User]` is not
merely more convenient than `next() -> User?`; it is the shape that avoids a 1.6× penalty
the caller cannot otherwise remove, because the penalty comes from a restriction
(`@inlinable` on generated bodies) that no amount of care at the call site can work around.

That is worth more than the number: it means the columnar batch path is not just a
performance option for Parquet, it is **the correct integration point for any driver**, and
`docs/KEYED-SOURCE.md` now says so.

---

# Validating a value you already have

**2026-08-10.** `docs/VALIDATE.md`. Running a schema's `@Validate` rules and `@Check`
functions against a value something else produced. One question decides whether the entry
point is worth having: is it cheap enough to sit next to somebody else's decode?

## The seam costs nothing of its own

The rules cost is isolated by decoding the same six-field document through a schema with
rules and one without. That difference is exactly what `validate` re-runs.

| operation | ns |
|---|---|
| decode, schema WITH rules | 462 |
| decode, same schema NO rules | 376 |
| **validate a constructed value** | **76** |

87 ns of rules inside a decode; 76 ns standing alone. The entry point is the rule engine
called from a second place, and adds no overhead of its own.

## Over a batch

| rows | ns | per row | vs a full decode, 471 ns |
|---|---|---|---|
| 64 | 5,229 | 82 | 0.174× |
| 1,000 | 82,170 | 82 | 0.175× |
| 20,000 | 1,634,600 | 82 | 0.174× |

Flat, and 72 ns of it is the rules — the remainder is the array element copy. Validating a
row costs **a sixth of decoding the document again**, which is the comparison that matters:
re-decoding is the alternative this entry point exists to avoid.

### That last column has now been wrong twice, and the reason generalises

It read 1.6× until 2026-09-11, against a **hard-coded 53**. The columnar arm had gone from
53 ns/row to 11 on 2026-09-10, and this arm divided by a constant somebody had copied out
of that arm's output months earlier. Nothing failed: the table still printed, the ratio
still looked plausible, and the conclusion drawn from it — "validating a row costs somewhat
more than decoding it" — was off by 5×.

**A constant copied out of another arm's output is a number with no owner.** The floor was
re-measured inside this arm, from the same store the columnar arm built, so the two could
not drift again.

**Then the columnar arm was deleted on 2026-09-12 and took the baseline with it** — and
this table went on being quoted in the headline as "84 ns/row batched" when no arm printed
a per-row figure at all. The paragraph above described a fix that was no longer in place.
Same screw, third turn, one day later, in the document that had just finished explaining
the lesson.

The baseline is now the one thing that cannot be deleted out from under this arm: a full
decode of the same document, measured four lines higher in the same run. It is also the
comparison a reader wanted — *is validating cheaper than decoding again?* — rather than one
borrowed from a feature that no longer exists.

### Two things that were not obvious

**`@inlinable` on the four entry points is worth 2×.** They are generic over `Self` and over
the sequence, they live in a source package, and the call site is in the user's module —
hard constraint 5's exact case. Without it the batch measured **176 ns/row**; with it, 84,
which is the single-value cost plus the copy. The gap was the unspecialized loop running
through witness tables, not the rules.

**One `[PathComponent]` array for the whole batch, rewritten in place.** The obvious
`[.index(i)]` inside the loop allocates per row; reusing the buffer is worth ~16 ns.

## The rule engine, put under a microscope

A rule that is 4% of a decode is invisible. The same rule called per row over a million rows
is not, and building this entry point is what forced the measurement.

| rule | before | after |
|---|---|---|
| `.range(13...120)` on `Int` | 8.9 | 8.6 |
| `.min(3)` on `String` | 22.4 | 14.0 |
| `.max(64)` on `String` | 22.4 | 14.2 |
| `.min(1)` on `[String]` | 9.9 | 11.0 |
| `.email` | **178.8** | **25.1** |
| `.url` | 42.0 | 21.4 |
| `.uuid` | 50.5 | 28.5 |

Nanoseconds, one rule per type against the same value, minus a fixed per-call cost that is
itself measured (by comparing one `.range` against two identical ones on the same field,
rather than assumed from a floor — subtracting a floor you guessed is how a per-rule table
ends up reporting negative numbers).

`.email` at 179 ns was 8× the next most expensive rule, and the algorithm was not the
problem. `isEmail` built `Array(s.utf8)` then `Array(domain)`; `isHostname` split the domain
into `[[UInt8]]`, one array per label plus reallocating appends; `isTrimmed` built a
`Set<UInt8>` per call. Roughly six heap allocations to check fifteen bytes.

**The obvious fix made one case worse.** Walking `String.utf8` directly with indices removed
every allocation and took `.uuid` from 50 ns to **61** — `String.UTF8View.Iterator` carries a
representation check per byte that `Array` iteration does not, and over 36 bytes that
outweighed the malloc it saved. The shape that works is neither: take the contiguous buffer
once with `withUTF8`, turn it into a `Span` at that single seam, and walk that. Every
validator below the seam is ordinary safe Swift, and the file emits *fewer*
strict-memory-safety warnings than the allocating version it replaced.

`.min`/`.max` on a `String` carried a second cost: `String.count` is grapheme-cluster
segmentation. That is the correct meaning for a rule whose message says "characters", so it
stays — with a shortcut. If every byte is ASCII **and none is CR**, each byte is its own
cluster and the count is the byte count. CR is the only exception, and the reason this is not
simply "is it ASCII": `"\r\n"` is a single cluster spanning two ASCII bytes.

### How this is known to be a speedup and not a behaviour change

`Benchmarks/Sources/DiffFuzz/FormatOracle.swift` keeps the previous implementation verbatim —
`Array(s.utf8)`, `[[UInt8]]` and all — as an oracle, and requires the fast one to agree with
it over **40,062 strings × 6 checks**: 40,000 generated from an alphabet of the bytes these
validators branch on, plus a table of the cases that make them hard (empty labels, boundary
hyphens, the legal trailing dot, an all-numeric TLD, CR, combining marks, ZWJ sequences).
`characterCount` is checked against `String.count` itself.

The differential was itself checked, by deliberately deleting the CR condition: it fails, and
names the strings.

## Compile time

`_assayCheck` is emitted only for a type that declares a `@Validate` or a `@Check`, so a
rule-free type is unaffected. Best-of-three at 100 types, 10 fields:

| type shape | ms/type |
|---|---|
| no rules — the gated arm | 87 |
| rules, before `_assayCheck` existed | 90 |
| rules, with `_assayCheck` | 114 |

24 ms is the per-field cost paid once more over the same fields, which is what
`docs/COMPILE-TIME.md` §2's 7.3 ms/field model predicts. There is no fat in it, so
`Experiments/03-compile-time/gate.sh` gates it rather than optimising it away: 100 ms for a
rule-free type, 145 for a rule-carrying one (single-shot runs land near 128, so the margin
covers the spread rather than the best case).


---

# Linux, measured — and one ratio that inverts

**2026-08-15.** Every number in this file above this line is one arm64 Mac, and said so.
This is the second platform.

**Swift 6.3.3 on both sides**, same toolchain version, same corpus, same harness. Linux runs
under Apple's Virtualization.framework: aarch64, 2 vCPU, 4 GiB. That makes the *absolute*
timings meaningless — a virtualised 2-core box is not a machine anyone deploys on — but the
ratios are measured against a baseline running on the same box under the same conditions,
which is what makes them portable. A slow machine slows both sides.

| | macOS arm64 | Linux aarch64 |
|---|---|---|
| struct decode vs Foundation | 8.98x | **8.64x** |
| prefix + skip | 6.28x | **6.10x** |
| generic value model | 1.47x | **2.07x** |
| `[String: T]` dictionaries | 7.25x | **6.01x** |
| YAML node parse vs Yams | 6.69x | **7.68x** |
| YAML struct decode vs `YAMLDecoder` | 11.27x | **14.02x** |
| **XML tree parse vs Foundation** | **1.30x** | **0.54x** |
| vs yyjson, use case | 0.67x | 0.58x |
| vs yyjson, float-dense | 0.77x | 0.60x |
| UTF-8 validation, share of decode | 4.2% | 4.1% |

## The headline: the thesis is not a Darwin artefact

8.64x against 8.98x. The falsification condition in `docs/PERFORMANCE.md` — comfortably clear
ZippyJSON's 1.38x — is met on Linux by the same margin it is met on macOS. That was the
question worth answering, and the answer is that deleting the `Codable` boundary at compile
time is a structural win rather than a property of one platform's Foundation.

## The one that inverts, and why

**XML goes from winning by 1.30x to losing by 0.54x** — Foundation's parser is roughly twice
Assay's speed on Linux, where it was slower on Darwin. This is the largest platform
difference in the suite and it is not noise.

The reason is that "Foundation's `XMLParser`" names two different programs.
`swift-corelibs-foundation` implements `FoundationXML` over **libxml2**, a mature C parser;
Darwin's is the older Apple implementation. So the Linux row is Assay's hand-written Swift
against C, and the Darwin row is not.

Read with the asymmetry that was already stated for this arm: Assay builds and keeps the
whole document tree, while the Foundation baseline runs a counting delegate and keeps
nothing. Against C, doing strictly more work, half the speed is a coherent result rather
than a defect — but "Assay's XML is faster than Foundation's" is a **Darwin-only** claim and
must not be repeated without the platform attached.

## The rest

- **The generic value model is better on Linux** (2.07x against 1.47x), for the mirror-image
  reason: `JSONSerialization` on Linux is pure Swift, and on Darwin it is C.
- **The loss to yyjson is larger** (0.58x against 0.67x). yyjson is the same C on both, so
  this is Swift's own generated code being relatively further behind here.
- **YAML is better on Linux** in both arms. Yams wraps libyaml on both platforms, so the
  difference is on Assay's side.
- **The allocation gate passes**, with block counts reported as unavailable — `mallinfo2`
  gives bytes in use and no block count, and the harness reports nothing rather than guessing.

## What is still not measured, and will not be faked

**x86-64.** No x86-64 hardware was available, and running the suite under emulation would
produce timings that describe the emulator. `Experiments/01-jump-table`'s finding — N >= 10
lowers to a jump table, below that a balanced binary search tree — remains verified on arm64
only, and `sweep.sh` must be re-run on x86-64 before it is claimed there.

Two portability fixes to the harness were needed to get this far, and they are the reason no
Linux number existed before: `mallinfo2` is declared in `malloc.h`, which the Glibc module
does not re-export, and `XMLParser` lives in `FoundationXML` off Darwin.

**The differential suite still runs on macOS only**, and the reason is worth writing down
because the obvious fix is a trap. `DiffFuzz` needs to tell an `NSNumber` holding `true` from
one holding `1`, or `{"a": true}` and `{"a": 1}` become indistinguishable and the oracle
quietly stops testing the difference. The Darwin idiom is
`CFGetTypeID(n) == CFBooleanGetTypeID()`; Linux has no CoreFoundation. Substituting the
portable `strcmp(n.objCType, "c")` compiles everywhere and **costs about 20x on macOS** —
`objCType` is a message send per value where the CF comparison is two loads, and sampling the
process shows every cycle inside it. So the differential keeps the fast Darwin call and Linux
coverage waits for a check that is cheap on both. `swift test` (393 tests) already runs
identically on both platforms; it is only the oracle harness that is pinned.


---

# Making the XML parser faster, by profiling rather than by admiring libxml2

**2026-08-18.** The Linux measurement above put Assay's XML parser at 0.54x against
`FoundationXML`, which is libxml2. The obvious response is to study libxml2's tricks. The
useful response turned out to be simpler: **profile first**, because the top cost was not
anything libxml2 does cleverly — it was a Swift idiom doing far more work than it looks like.

Measured with `sample` on a 100 KB document with nested elements, attributes, text and
repeated tag names, best of five, back to back on the same machine.

| | MB/s | vs Foundation, macOS | vs libxml2, Linux |
|---|---|---|---|
| before | 89.1 | 1.30x | 0.54x |
| after | **156.2** | **2.38x** | **0.96x** |

**1.75x**, from three changes, none of them exotic. Against libxml2 that is parity — while
Assay builds and keeps a whole document tree that libxml2's SAX delegate never builds.

## What the profile actually said

The single largest cost was `String.firstIndex(of: ":")` in namespace resolution, which runs
once per element and once per attribute. On a `String` that iterates by **Character**, so
each step is grapheme breaking, `validateScalarIndex`, `_allASCII` and a full `String ==`.
That family of calls — `_uncheckedIndex(after:)`, `subscript.getter`, `_uncheckedFromUTF8`,
`_stringCompareWithSmolCheck` — came to roughly **half of all parse time**, well ahead of
anything doing real parsing work.

Searching `raw.utf8` instead is exact, not approximate: `:` is ASCII 0x3A, UTF-8 is
self-synchronizing, and no continuation byte can be 0x3A. Worth **1.50x on its own**.

This is the one lesson from libxml2 that transfers wholesale, and it is not a technique. C
has no Character abstraction, so libxml2 could not have written the slow version. Swift makes
the expensive spelling the default one.

## The other two

- **One pass, not two.** `parseText` scanned the run for `<` and `&`, built a String, then
  `normalizeLineEndings` walked the same bytes again looking for CR — and the same for
  attribute-value whitespace. Noticing CR in the loop that is already reading every byte is
  free. Worth 1.10x, and it is the habit libxml2 is built on.
- **No per-element `Set` or namespace scope.** Duplicate attributes were found with a
  `Set<XML.Name>` built per element, and a namespace scope dictionary was pushed for every
  element whether or not it declared one. Elements have a handful of attributes, where a
  linear scan over the array already being built beats hashing, and most elements declare no
  namespace at all — so `lookup` was walking a stack of mostly empty frames.

## What was tried and rejected

**Finding the colon inside `scanName`**, which already walks those bytes, so `resolve` would
need no search at all. It is the obvious next step after the above and it measured **167 MB/s
against 195**: one comparison per name byte, on every name, costs more than one `firstIndex`
over the handful of bytes a name has. Recorded in the source so it is not re-derived.

## Round two: allocations, and a lesson that cost more than the speedup

Profiling after round one put `parseElement` itself at the top — real work ahead of
overhead, which is the shape you want — with array growth as the largest remaining cost.
`_ArrayBuffer._consumeAndCreateNew` traced to three arrays built per element.

**`children.reserveCapacity(4)` is the whole win: 1.08x.** The 1→2→4 reallocation chain was
the single biggest allocation source in the parser. A leaf element over-reserves three slots
of a transient buffer, which is cheaper than the two reallocations it saves everywhere else.

**Deferring attribute names to byte ranges is NOT worth it, and is kept only because the
refactor around it is.** The idea is sound — most attribute names are examined and discarded,
since `xmlns` and `xmlns:foo` are declarations rather than attributes, so building a String
and then asking `hasPrefix("xmlns:")` (Character-based, the same cost `firstIndex` had) is
allocation and grapheme walking to throw the answer away. Measured: **+0.9% on ordinary
documents and +2% on attribute-heavy ones**. That is the honest number.

### The lesson, which is worth more than either

Moving that loop's locals into `parseElement` **blew the stack**. Not on a huge document — on
a 5,000-deep one, where the depth guard stops recursion at `Limits.maxDepth` (64) long before
anything is materialised. It surfaced as `SIGBUS` in the *amplification* suite, nowhere near
the code that caused it, and only because Swift Testing runs on threads with far less stack
than the main thread.

> **In a recursive descent parser, the recursive function's frame size is multiplied by the
> depth limit.** `parseElement` at `maxDepth` 64 must fit its frame in a thread stack 64
> times over. Inlining into it is a cost paid 64 times.

`scanAttributes` is therefore `@inline(never)` and takes its locals with it, and that is why
it survives even though the optimisation it carries is marginal: the extraction is a
robustness fix. Before it, the parser was one modest addition away from this failure, and
nothing said so.

## Tree against tree: the honest number is 0.87x, not 0.54x

**2026-08-19.** Every XML ratio published above compares Assay — which builds and KEEPS a
document tree — against Foundation's `XMLParser`, which runs a counting delegate and keeps
nothing. The asymmetry was stated each time, but a stated caveat is not a measurement, and
"0.54x against libxml2" was never a like-for-like claim.

Linking libxml2 directly and calling `xmlReadMemory`, so both sides build a full tree and
free it inside the timed region:

| records | bytes | libxml2 ns | Assay ns | ratio |
|---|---|---|---|---|
| 10 | 2,549 | 11,372 | 12,034 | 0.94x |
| 50 | 12,629 | 48,038 | 58,134 | 0.83x |
| 200 | 50,862 | 188,777 | 226,790 | 0.83x |
| 800 | 204,595 | 772,335 | 869,079 | 0.89x |

**mean 0.87x.** libxml2 is about 15% ahead at the same job — not the 85% the SAX comparison
implied. Both parse the same documents and the element counts are asserted equal before
timing. (macOS, system libxml2 from the SDK; the harness is a throwaway package linking
`libxml-2.0`, not committed, because vendoring libxml2 the way `CYYJSON` is vendored is a far
larger undertaking than the number justifies.)

That reframes what is left to do. 15% is within reach; 85% would not have been.

## Tried and rejected: word-at-a-time structural scanning

quick-xml uses `memchr` to find `<`, and the same trick works without intrinsics — the SWAR
test `(v &- 0x0101…) & ~v & 0x8080…` finds a zero byte, so applied to `v ^ needle` it finds a
needle, and three needles (`<`, `&`, CR) are three ORed tests over one loaded word.

Implemented, correct, all 393 tests pass, and **worth nothing**: 202.7 MB/s before, 202.2
after, with the libxml2 ratio unmoved at 0.87x.

The reason is the shape of real XML rather than anything wrong with the technique. Text runs
in a document are mostly SHORT — `<tag>alpha</tag>` is five bytes, an element name is under
ten — so the eight-byte loop rarely completes an iteration and the three broadcast constants
are pure setup. It is the same lesson `docs/PERFORMANCE.md` §14 recorded when retiring the
SIMD phase for JSON: the scan was not where the time was.

## Interning: measured, and REJECTED

libxml2's `xmlDict` interns names, so a document saying `<tag>` a thousand times allocates
one string and compares by pointer. It is the most-cited idea in fast XML parsing, and the
profile pointed straight at it: String construction (625 samples) plus the ARC release that
follows (662) together beat the parsing itself.

Built properly — a direct-mapped cache keyed on the name's bytes, hash never trusted without
a byte comparison, storing each name **already split** at its colon so a repeat never
searches again.

| | mean, tree vs tree |
|---|---|
| no cache | **0.87x** |
| 512-slot cache | 0.54x |
| 64-slot cache | 0.43x |

**Worse, and worse again when made smaller.** Two reasons, both about Swift rather than
about caching:

1. **The setup is not free.** Five parallel arrays of 512 slots is ~25 KB allocated and
   zeroed per parse. A 2.5 KB document measured **0.26x** — the cache cost ten times what
   the parse did. Shrinking to 64 slots trades that for collisions, so the miss path pays
   hash, verification *and* construction: 0.43x.
2. **The thing being cached is already cheap.** Swift's small-string form keeps any name
   under 16 bytes off the heap entirely, so building `tag` is a register-width copy.
   `xmlDict` wins in C because there every string is a `malloc`. Hashing n bytes and then
   verifying n bytes, through a bounds-checked accessor, cannot beat a memcpy of n bytes
   that never touches the allocator.

The general lesson outlasts the specific result: **a technique that is decisive in C can be a
pessimisation in Swift, and the reason is usually that the stdlib already solved the problem
the technique exists for.** The same shape appeared in `FormatValidators`, where walking
`String.utf8` "to avoid an allocation" was slower than the allocation.

## Flat node storage: no longer indicated

An earlier version of this document named it as the next step. That was written against a
profile taken BEFORE `children.reserveCapacity(4)` landed, and it does not survive the one
taken after: `_ArrayBuffer._consumeAndCreateNew` has dropped out of the top thirteen
entirely.

roxmltree's design — one vector for the whole document, parent and child links as indices,
nothing allocated per node — removes per-element array allocation, and per-element array
allocation is no longer what this parser spends its time on. It would be a large public-API
change bought with a stale measurement. Recorded so the idea is not picked up again from the
older text.

## Round three: the same function, a third time

`resolve` has now been the top or near-top cost three separate times, and each fix uncovered
the next layer of the same mistake.

| spelling | cost |
|---|---|
| `raw.firstIndex(of: ":")` on a `String` | ~half of all parse time |
| `raw.utf8.firstIndex(of: ":")` | 236 samples, third largest |
| `r.byte(absolute:)` over the range already in hand | gone |

`String.utf8` looks like a byte view and is not: it carries a representation check per byte,
which is the same trap `FormatValidators` hit. Searching the SOURCE bytes over a range the
scanner already produced is the same number of comparisons through a plain bounds-checked
load, and it builds no intermediate `String` for the unprefixed case — which is nearly every
name. **+3.6%.**

Also tried, and worth 0.5%: hoisting the pointer out of the closure passed to
`String(unsafeUninitializedCapacity:)`, so it captures two trivial values rather than
reaching through a `~Copyable` `self`. Structurally right and almost free of benefit — the
samples a profile attributes to `partial apply for closure #1` there are the memcpy itself,
not thunk overhead. Recorded so it is not chased twice.

## Round four: two ideas measured, both closed

**`children.reserveCapacity(4)` is optimal, and now measured rather than guessed.**
`XML.Node` is 57 bytes with a stride of 64, so reserving four slots claims 256 bytes per
element and a leaf with one text child uses 64 of them. That sounds wasteful enough to be
worth tuning, and it is not:

| reserve | MB/s |
|---|---|
| none | 191.3 |
| 1 | 194.3 |
| 2 | 200.2 |
| **4** | **207.9** |
| 8 | 203.0 |

**Shrinking `XML.Name` cannot be done.** The idea was to store the namespace as an index into
a per-document table and expose `namespaceURI` as a computed property — halving the
refcounted fields on every element, and shrinking `Name` from 32 bytes to about 20, which
would take `XML.Node`'s stride from 64 to 48 and cut array traffic by a quarter.

The prize is real but small: a document with a realistic 61-byte namespace URI parses **4-5%
slower** than the same document with an 11-byte one, at identical node count, because a URI
under sixteen bytes lives in Swift's small-string form and is not refcounted at all while a
longer one is retained once per name.

It is not reachable. A computed `namespaceURI` needs the table; reaching the table from a
`Name` costs a stored reference, which is the field being eliminated — 16 bytes of `String?`
for 8 bytes of table reference plus 4 of index saves four bytes and adds an ARC field and a
lifetime hazard. The alternative, moving the accessor to the document
(`doc.uri(of: name)` instead of `name.namespaceURI`), is an API change that makes the common
case worse to use. Measured, closed, and written down.

## Where the remaining gap is, and why it is not reachable

String construction and release is roughly **43% of parse time**, and that is structural
rather than sloppy: `XML.Node` owns its Strings because it is a public `Sendable`, `Hashable`
value type that outlives the input buffer.

libxml2 does not pay that. pugixml and RapidXML pay less still — they parse **in situ**,
mutating a copy of the input to terminate names in place and storing pointers into it, which
is how they beat libxml2 by 2-4x. Every one of those designs has nodes that BORROW the input.

In Swift that is `~Escapable` in the public surface. This library refused it for
`AssayReader`, refused it again for `KeyedSource`, and `docs/KEYED-SOURCE.md` records what
the second refusal cost. **The remaining gap to libxml2 is, quite precisely, the price of
that decision** — 13%, for a value type that cannot dangle.


---

# x86-64, at last — and the XML row that flipped back

**2026-08-20.** `.github/workflows/benchmark.yml`, native on a GitHub-hosted x86-64 runner.
This closes the caveat every ratio in this file has carried since the project began.

| | macOS arm64 | Linux aarch64 | **Linux x86-64** |
|---|---|---|---|
| struct decode vs Foundation | 8.98x | 8.64x | **10.89x** |
| prefix + skip | 6.28x | 6.10x | 5.96x |
| generic value model | 1.47x | 2.07x | **3.15x** |
| `[String: T]` dictionaries | 7.25x | 6.01x | 6.50x |
| YAML node parse vs Yams | 6.69x | 7.68x | 7.16x |
| YAML struct decode | 11.27x | 14.02x | 13.51x |
| **XML vs Foundation** | 2.26x | 0.54x → | **1.39x** |
| UTF-8 validation, share of decode | 4.2% | 4.1% | 4.6% |

**The thesis is strongest on x86-64.** 10.89x, against 8.98x on the machine it was developed
on. Deleting the `Codable` boundary at compile time is not a Darwin artefact and not an arm64
artefact.

**The XML row flipped back, and that is the parser work rather than the platform.** When
Linux was first measured (2026-08-15) XML was **0.54x** against `FoundationXML`, which is
libxml2 — the single loss in the suite, and the reason for the optimisation rounds above. The
same comparison now reads **1.39x**. Assay's XML parser is faster than libxml2-backed
Foundation on Linux while building and keeping a whole document tree that Foundation's SAX
delegate never builds.

**The generic value model widens as Foundation gets slower**: 1.47x on Darwin where
`JSONSerialization` is C, 2.07x on aarch64 Linux, 3.15x on x86-64 Linux where it is pure
Swift. That row says more about Foundation's platform split than about Assay.

## The crash that only x86-64 could find

The first x86-64 run did not produce these numbers. It died with `SIGSEGV` in
`swift_release`, inside `AllocFailures.__deallocating_deinit`, during global teardown and
nowhere near the cause.

The cause was three commits old. Getting the benchmark to build on Linux needed `mallinfo2`,
which is declared in `malloc.h` and not re-exported by the Glibc module, so it was declared
in Swift and reached with `@_silgen_name`. That is ABI-unsound: `mallinfo2` returns a
ten-field struct **by value**, and how a large struct is returned is target-specific —
aarch64 passes it in registers, x86-64 SysV passes a hidden pointer. The mismatch corrupted
memory, and the corruption surfaced only at exit.

It is now behind a one-function C shim returning a `size_t`, so the struct return never
crosses the language boundary.

That bug was written, built clean, and ran green on macOS **and** on aarch64 Linux before
being pushed. A second *architecture* found it in one run. "Every published ratio is one
arm64 Mac" was a caveat about numbers; it was also hiding a crash.


## `@Key(path:)` against the nested-`@Schema` alternative — 2026-09-08

`Benchmarks/Sources/AssayBench/KeyPathBench.swift`, macOS/arm64, release.

The ship-or-refuse rule was written **before** the number, which is the only way such a rule
means anything: within 1.15x of the nested-`@Schema` alternative, or `@Key(path:)` does not
ship and `ROADMAP.md` §3's stated fallback ("the honest answer is a nested @Schema type")
remains the right answer.

```
shape              bytes   nested ns    paths ns     ratio
4 leaves             170         419         411     0.98x
+3 plain keys        208           -         469     1.14x
```

**0.97-1.01x over four runs.** GATE PASSED.

**Read this as "the walk costs no more than the nesting", not "paths are faster."** The two
arms decode byte-identical documents, but they do not produce the same thing: `nested`
materialises two extra structs the caller then has to reach through, and `paths` produces the
four leaf values directly. That asymmetry favours `paths` and is why the ratio sits at 1.00
rather than above it. The claim the gate was written to test is that a path does not cost a
second pass, and that is what 0.98x shows.

The second row is a different question — whether a group costs one dispatch arm or one per
field. Adding three ordinary keys to a schema with four path fields costs 1.14x of the
four-field version, which is the cost of three more keys and not of the paths.

Compile time is **reported, not gated**, exactly like the `arrays` arm beside it: **101.4
ms/type** where every field is behind a path (five groups of two), against 71.8 ms for the
flat scalar arm the 100 ms budget was calibrated on. `Experiments/03-compile-time/gate.sh`
prints both.


## Cold start — first measured 2026-09-09

`Benchmarks/Sources/AssayBench/ColdStartBench.swift`, macOS/arm64, release.

`CLAUDE.md`'s "Start here now" listed this as item 2, with the claim *"a macro emitting no
`CodingKeys` should win structurally"* — and `ROADMAP.md`'s verification table flagged it as
"exactly the kind of should that this file exists to stop anyone asserting". **The claim
holds.**

```
decoder          median us    total us    max us
JSONDecoder            8.4         581        42
Assay                  1.1         107        32

first decode:              7.7x, 7.9x   (two runs)
steady state, same shape:  6.6x, 6.8x
```

**First decode is a LARGER advantage than steady state** — 7.7–7.9× against 6.6–6.8× — so the
one-time per-type work is where the gap is widest. Subtracting steady state from first decode
leaves ~0.8 µs of one-time cost for Assay against ~6.3 µs for `Codable`, which is the
`CodingKeys` metadata and container machinery that a macro simply does not create.

**Method, and one statistic that matters.** A type can be decoded for the *first* time exactly
once per process, so a loop measures steady state. This is **60 distinct types, one sample
each**, alternating between the two decoders so neither gets a warmer allocator.

The headline is the **median of the per-type samples, not the total**. An earlier total-based
version of this arm reported 3.3×, 5.8× and 5.2× on three runs of the same build: a handful of
first-of-everything outliers (the `max` column: 32–42 µs against a 1–8 µs median) dominate a
sum of sixty samples. The median moves by a few percent across the same runs. Both are printed.

Process start — dyld, image loading — is a different thing that this does not measure, and it
is dominated by linking Foundation at all rather than by either decoder.

## Multi-megabyte documents — first measured 2026-09-09

`Benchmarks/Sources/AssayBench/LargeDocBench.swift`. **Not a target band**, and
`docs/PERFORMANCE.md` §14's "Assay claims no advantage on multi-megabyte documents" still
stands. What was missing was a number: "we do not optimise for it" and "we have not looked" are
different sentences.

```
items           MB  Foundation     Assay    ratio  Assay MB/s
2000           0.2      1.9 ms    0.3 ms    6.90x         704
20000          2.0     19.6 ms    3.0 ms    6.63x         689
80000          8.3     78.4 ms   11.9 ms    6.60x         696
```

**A prediction written into the harness before the run was wrong, and is recorded rather than
edited out.** The reasoning was that output allocation must come to dominate — ten thousand
`String`s reach `malloc` however they were parsed — so the ratio should shrink towards 1.0.
It does not: 6.90× to 6.60× across a 40× size range, with throughput flat at ~700 MB/s.

The reading that survives is stronger than the one predicted: **the advantage is per-value, not
per-document.** Foundation's cost scales with the number of decoded values exactly as Assay's
does, because the container boundary is crossed per value — so identical output allocation on
both sides cancels rather than converging. Nothing falls off a cache cliff at 8 MB either,
which is what a cache-shaped advantage would have done.


## Total malloc traffic — first measured 2026-09-09

`Benchmarks/Sources/AssayBench/TotalAllocations.swift`, macOS/arm64, release. **Darwin only.
Reported, never gated.**

The last unqualified "unmeasured" in `ROADMAP.md`'s verification table. The live-block gate
beside it structurally cannot see an allocation that is made and freed inside a decode, and
`.mallocCountTotal` needs jemalloc installed beside the toolchain and cannot run on the musl or
wasm legs. The row said closing it would be "either a bounded Darwin/Linux-only addition or a
permanent gap, and it should be recorded as whichever it turns out to be."

**It was a bounded Darwin-only addition, and it needed no jemalloc.** `malloc_logger` is the
global hook `MallocStackLogging` itself installs; setting it in-process makes the allocator
call back on every allocate and deallocate, *exactly* — none of the nano zone's batching that
makes the live-block harness undercount 10–15%.

```
self-check: 100 exactly-sized [Int] allocations counted as 108 allocs / 108 frees

shape             Foundation     Assay    ratio  transient
1 items                   25         6    4.17x         19
10 items                  94        55    1.71x         39
50 items                 378       257    1.47x        121
```

**This is the arm where the Foundation comparison is worth something.** The live-block harness
carries an explicit limitation that it cannot compare two decoders retaining the same data —
Assay and Foundation hold identical `String`s and `Array`s, so they hold identical blocks and
the comparison is vacuous there. Here the retained output cancels on both sides, so the whole
difference is **transient**: intermediate containers, boxed values, per-key machinery. That is
precisely what the decode thesis is about, and it was the one thing the existing gate could not
see.

**Why it is not gated.** "Is the live footprint of one decoded value the size the design says?"
has a right answer — an `[Int]` of 800 must be one exactly-sized allocation. "How much work did
the allocator do?" does not: it moves with every stdlib version, and gating on it would fail CI
for a change to `String`'s growth policy.

**Symbol interposition was rejected with a reason rather than left untried.** Defining `malloc`
in the executable interposes on Linux; on Darwin it does not, because two-level namespace
binding means `swift_slowAlloc` in libswiftCore.dylib is already bound to libsystem_malloc's
`malloc` and never consults anything the main executable defines. Making that work needs
`DYLD_INTERPOSE` in a separate dylib plus `DYLD_INSERT_LIBRARIES`, which `swift run` cannot
arrange.

**Linux remains open.** `mallinfo2` reports bytes, not counts, and no equivalent hook exists.
The arm prints "unavailable" there rather than a guessed number.


## ZippyJSON — first measured 2026-09-09, and it is the comparison the thesis is stated against

`Benchmarks/Sources/AssayBench/ZippyBench.swift`, macOS/arm64, release, ZippyJSON 1.2.x built
as its own manifest specifies.

`CLAUDE.md`'s falsification condition names this decoder by name:

> if a scalar Swift phase-1 implementation does not comfortably clear ZippyJSON's 1.38× over
> Foundation on the corpus in `docs/PERFORMANCE.md` §12.2, the thesis is wrong and the SIMD/C
> work is moot.

and so does the argument it rests on: *"ZippyJSON bolted simdjson onto `Decodable` and got
1.38× over Foundation."* **Until now that 1.38× was a citation** — someone else's machine,
someone else's corpus, and the *legacy* Darwin JSON decoder rather than the swift-foundation
rewrite this harness compares against everywhere else.

```
items       bytes  Foundation     Zippy     Assay   Zippy/F   Assay/F   Assay/Z
1             285        3148      1904       458     1.65x     6.87x     4.15x
10           2221       17118      9048      2926     1.89x     5.85x     3.09x
50          10821       77034     39338     12969     1.96x     5.94x     3.03x
200         43072      302197    154211     51088     1.96x     5.92x     3.02x
```

Three runs: the `Assay/Z` column reads 2.94–3.15× at 10 items and above, 3.88–4.15× at one.

**The thesis is confirmed in its strongest available form.** Assay is scalar Swift with no SIMD
anywhere — phase 4 was retired unbuilt — and it decodes **3.0× faster than a decoder with
simdjson underneath**. The only structural difference is that ZippyJSON has a
`KeyedDecodingContainer` and Assay does not. If the container boundary were not the dominant
cost, that column could not be above 1.0.

**The comparison is not flattering Assay by hobbling ZippyJSON — the opposite.** ZippyJSON
measures **1.65–1.96× over Foundation here**, comfortably *better* than the 1.38× it was cited
at, because the harness gives it a payload shape it does well on and builds it as its own
package specifies. It is doing better than its published number and still loses by 3×.

Fairness, since a rigged comparison proves nothing: same bytes and same struct shape for all
three; both decoders constructed once outside the loop; Assay decodes from `[UInt8]` and the
other two from `Data`, each its own native input, because converting either would measure a
bridge; and all three must produce equal field values before any of them is timed.

**Still not measured: simdjson directly.** That needs a C++ interop shim, and it answers a
different question — "how fast is the parser?" — which yyjson already answers (Assay loses
0.65× on the use-case arm, published above). The question this arm answers is the one the
thesis is about: that same class of parser, *wired to `Decodable`*.

Darwin/arm64 only. `ZippyJSON` is a benchmark-package dependency and is not linked by anything
the library ships.

---

## TOML: a fourth tree decoder, against C++

**2026-09-10.** `AssayTOML` shipped with the same caveat as YAML and XML: it is a tree
decoder — `TOML.Node`, then `RawValue`, then the struct — so no `Codable` boundary is
deleted and the JSON thesis does not apply. The baseline is **toml++** (C++, the most
conformant implementation) reached through TOMLKit's wrapper, which is what a Swift project
would otherwise use. The corpus is the `apimodel` ladder rendered with `[[items]]` sections
by `CorpusRender.renderTOML(sections: true)` — the same bytes `DiffFuzz toml` verifies both
parsers agree on before this arm times them.

```
$ swift run -c release AssayBench toml

TOML node parse — TOML.parse vs TOMLTable(string:) (toml++)
size           bytes      toml++ ns     Assay ns     ratio
512b             858           9118         8041     1.13x
2k              2299          24096        21208     1.14x
8k              8463          86503        77094     1.12x
32k            33879         347015       331200     1.05x
64k            67420         690974       695518     0.99x
mean 1.09x over 5 sizes

TOML struct decode — T.parse(toml:) vs TOMLKit's TOMLDecoder (Codable)
size           bytes TOMLDecoder ns     Assay ns     ratio
512b             858          17081         8889     1.92x
2k              2299          43260        23045     1.88x
8k              8463         154686        83216     1.86x
32k            33879         612269       350872     1.74x
64k            67420        1218893       734446     1.66x
mean 1.81x over 5 sizes
```

Parity with a C++ parser on the tree — scalar Swift building a `TOML.Node` against toml++
building a `toml::table`, and the wrapper's crossing is in the toml++ column, stated rather
than hidden. The struct-decode row is the one a migrating project makes, and its 1.81× is
mostly TOMLKit's `Codable` decoder walking the tree a second time. Nothing here has been
profiled yet; the per-line `[KeySegment]` array and the `TableBuilder` class per `[[items]]`
section are the obvious first targets if the number ever matters.

---

## Columnar: the per-row allocation that was wrongly closed

**2026-09-10.** A slow re-read of the columnar path, prompted by the question "is it
written efficiently?", measured the generated `_assayBatch` against a hand-written floor
with the decoded values consumed:

```
$ swift run -c release AssayBench colfloor        (before)
           floor: direct indexing, no checks       9.2
  hoisted: same semantics, checks per column       9.6
    generated _assayBatch, called concretely      52.6
  generated, via batch(from:) [protocol ext]      57.2
```

Five times off the floor, and the `pathab` arm placed the real body with the *eager*
hand-rolled arm (54 ns), not the lazy one (15) that the 2026-09-07 record said it was
byte-identical to. The cause was the one haul's report had named: `let path = path +
[.index(__r)]` at the top of the row loop, an allocation per row for a diagnostic path a
clean batch never reads.

The fix is not the one proposed. The generated loop now writes two integers into the sink
(`IssueSink._enterRow(row, depth:)`) and `sink.add` — cold — inserts the row index into
anything reported during that row, so a rule failure and a `@Fallback` warning get it too
without the rule engine changing. There is no per-row path anywhere in the body.

```
$ swift run -c release AssayBench colfloor        (after)
           floor: direct indexing, no checks       9.7
       hoisted: same semantics, hand-written      10.6
    generated _assayBatch, called concretely      11.2
  generated, via batch(from:) [protocol ext]      13.3

$ swift run -c release AssayBench columnar
rows         row-wise ns    batch ns   per row  batch wins
64                  5313         663        10       8.02x
1000               81140        9353         9       8.68x
20000            1718208      193562        10       8.88x
100000           8496875     1009146        10       8.42x
batch generic-over-schema costs 1.13x

$ swift run -c release AssayBench columndecodable
                   Int64, built in      416083      4.16
           Micros, ColumnDecodable      405542      4.06
```

Every columnar number in this file above this section was measured with that allocation in
place; the ratios that were the point of each table (hook vs built-in 0.97×, generic vs
concrete 1.13×) survive, the absolutes do not. The allocation gate could never have seen it
— a block freed within the row is not a live block — so the `colfloor` arm is the guard
now, and the gate gained a columnar row for the retained side. `ROADMAP.md` carries the
record of how a correct report was closed as wrong; the `DiagnosticPathBench.swift` header
is the corrected version of the claim it used to make.

---

## Rows: the transpose, measured seven times

**2026-09-11.** `docs/ROWS.md`. `RowBatch` is the transpose a row-shaped source would
otherwise write, and it was rebuilt seven times against a profile before it was committed —
the table in ROWS.md §2 is the record, and the short version is that three things a Swift
struct does by default each cost more than the work: dynamic exclusivity on a class's stored
property (CLAUDE.md rule 3), a borrowed `String` parameter (a retain/release pair per cell),
and a read-modify-write of a mask through `inout self` (serialised on store forwarding). The
gate written first — within 1.2× of a hand transpose — was missed at ~1.45× and shipped with
the number; the remaining ~1.5 ns/cell is state reloaded from an `inout` struct that any
call-per-cell API pays.

```
$ swift run -c release AssayBench rowbatch

Row-shaped sources — rows in, structs out (200k rows, 8 columns, 4 of them String)
     RawValue per row, tree path (the old route)      70.5
   hand transpose + batch (what a driver writes)      28.0
                           RowBatch fill + batch      40.4
   RowDecoder, flush every 4096 (the driver API)      42.3
                    fill only: RowBatch, 8 cells      26.2
              fill only: hand transpose, 8 cells      16.9
          fill only: bare pointer-to-[T] appends      13.4
               direct ColumnarSource (the floor)      11.0

The write side: field values out of a @Schema value, 200k rows
       _assayEncodeRaw (a RawValue tree per row)      59.3
                  encodeRow into a counting sink       1.3
```

---

# A full re-run, and the constant that had no owner

**2026-09-11.** The table at the top of this file was regenerated from one complete
`swift run -c release AssayBench`, because two of its rows had been amended by hand after
the value-model fix while the header still credited the older run. A table whose rows come
from different runs is a table nobody can reproduce.

Everything moved by a few percent, which is this machine's run-to-run spread, and nothing
changed its conclusion. The rows worth naming:

| arm | was | now | why |
|---|---|---|---|
| generic value model | 3.11× | 3.16× | noise; the real move was 1.51 → 3.11 the day before |
| yyjson, DOM vs DOM | 0.13× | 0.14× | noise |
| TOML node parse | 1.09× | 1.17× | noise, and the arm is close to parity either way |
| TOML struct decode | 1.81× | 1.95× | noise |
| `T.validate(_:)` batched | 1.6× the columnar floor | **7.9×** | **not noise — see below** |

## The bug this run found

`ValidateBench` prints validation cost as a multiple of "a fast decode", which is the
question the whole entry point turns on: a column store that decodes a row in tens of
nanoseconds will not call a validator that costs hundreds.

It computed that multiple by dividing by **53**, a literal, copied out of the columnar
arm's output when both were written. The columnar arm went to ~11 ns/row on 2026-09-10 when
a per-row path allocation was removed. This arm kept dividing by 53.

So it printed `1.57×` where the truth was `7.91×`, and it did that in a table headed "As a
fraction of a fast decode — the seam this entry point exists for". Nothing failed. No test
covers a benchmark's own arithmetic, the ratio looked plausible, and the sentence drawn
from it in this file — *"validating a row costs somewhat more than the fastest decode Assay
has"* — read as a finding rather than as a division by a stale literal.

`docs/VALIDATE.md` had already been fixed by hand on 2026-09-10, which is the part worth
sitting with: **the prose was corrected and the instrument was not.** The next person to run
the arm would have got 1.57× again and had every reason to trust it over the document.

The fix is not "update the 53". The arm measured the columnar floor in the same run, from
the same `makeStore` the columnar arm used, and printed the measured value in the column
header so the two could not silently disagree:

> **That fix did not survive the week.** The columnar arm was deleted on 2026-09-12 and
> `makeStore` went with it, so the baseline vanished and the headline kept quoting a number
> nothing printed. The arm now divides by a full decode it measures itself. A baseline
> borrowed from another arm is safe only while that arm exists.

```
As a fraction of a fast decode — the seam this entry point exists for
rows         validate ns   per row  vs 11 ns/row
--------------------------------------------------
64                  5367        84         7.91x
1000               85049        85         8.02x
20000            1653110        83         7.79x
100000           8413958        84         7.93x
```

**A constant copied out of another arm's output is a number with no owner.** It belongs to
neither arm: the one that produced it does not know it was copied, and the one that uses it
cannot tell when it went stale. This is the same family as the three eager-diagnostic-path
allocations — a cost nothing asserts on — with the twist that here the wrong number was
being *printed*, in a table, under a heading that said what it meant.

Worth grepping for the next time: any benchmark arm dividing by a literal it did not
measure.

---

# `ColumnDecodable` was never free, and the instrument said it was

**2026-09-11.** The full re-run above was supposed to be bookkeeping. One row did not
reproduce.

| | recorded 2026-09-10 | three runs, 2026-09-11 |
|---|---|---|
| `Int64`, built in | 4.16 ns/row | 3.75 / 4.02 / 3.75 |
| `Micros`, `ColumnDecodable` | 4.06 ns/row | 6.69 / 7.68 / 7.30 |
| ratio | **0.97×** | **1.66× / 2.02× / 1.95×** |

The built-in column agrees. The hook does not, and not by a little.

## It is not a regression

The obvious suspect was the row work — `RowBatch`, text cells, `@Check` on the batch path —
all of which edited the columnar emitter after that measurement. It is not that. Checked out
`1fef8b6`, the first commit after the per-row allocation fix and before any of it:

```
                   Int64, built in      407778      4.08
           Micros, ColumnDecodable      733834      7.34
the hook costs 3.27 ns/row over the built-in column (1.80x)
```

**1.80×, at the commit the 0.97× was supposed to describe.** Nothing regressed. The number
in the documents was not reproducible when it was written.

(A second worktree, at a commit from before the allocation fix, measured 41.04 vs 41.61 —
1.01×. That is the honest version of the old claim: with 38 ns of malloc on both sides, the
two are genuinely indistinguishable.)

## Where the 3 ns actually goes

In the expansion, and it has been there since the feature shipped. A built-in column's
validity mask is pulled once, before the row loop. A `ColumnDecodable` column's is projected
out of the column struct inside it — and so is the metadata, a second time, as an argument:

```swift
// Tests/AssayTests/Goldens/sources.swift.golden, inside `for __r in ...`
if let __col1 = __c1, __r < __col1.count,
   !Assay._assayIsNullAt(__n1, __r) {                       // built in — __n1 is hoisted
    __f1 = __col1[__r]

if let __col4 = __c4, __r < __col4.count,
   !Assay._assayIsNullAt(__col4.nulls, __r) {               // hook — per row
    __f4 = Date(assayColumn: __col4, row: __r, metadata: __col4.metadata)
```

`SourceGen.swift` chooses between them in one ternary, and the custom arm simply never got
the hoist. Adding it is the obvious fix and is **not** made here: it is a codegen change and
wants goldens, tests and the compile-time gate, none of which belong in a documentation
pass. A field that already has a text fallback is emitted a hoisted `__n` it then does not
use in the typed branch, which is a hint at how small the change is.

## The lesson, which is the reason this entry exists

Three separate wrong numbers turned up in one afternoon of regenerating a table:

1. `ValidateBench` divided by a hard-coded `53` after the thing it named went to 11.
2. `ColumnarBench` divided by a repeated literal `200` rather than by its own row count.
3. This one — a ratio that was never reproducible, kept because it agreed with the design.

The first two are stale constants. **This one is different and worse**, because the original
reading was *correct for the instrument that took it*: with 38 ns of allocation on both
sides, 0.99× is what the arm genuinely reported. Removing that allocation made the
measurement newly capable of resolving a 3 ns difference — and nobody re-derived the
conclusions that predated it. They were re-confirmed instead, by a measurement recorded the
same day that does not reproduce on the same commit.

**When a fix makes an instrument more sensitive, every conclusion that instrument produced
before the fix is unverified again.** Not wrong — unverified. The columnar allocation fix
made four arms sharper; this is the one that had a claim resting on the blur.

And the claim that mattered is unharmed. The argument for `ColumnDecodable` was never "the
hook is free"; it was "the generic call happens once per column instead of once per row",
against a `KeyedSource` shape measured at 57× the concrete call. 3 ns/row is a price. A
witness call per row was the reason the other path was deleted.

---

# Writing seven recipes found two bugs, and one of them was the feature's own use case

**2026-09-11.** A "Recipes" section for the website: seven whole programs, each compiled
and run by the docs build so the output on the page is what it printed. The constraint was
editorial — a recipe that cannot be written as a working program is a guide page in
disguise — and it turned out to be a test harness.

## 1. The handler that answered 415 with a body saying 422

The first recipe is an HTTP endpoint. It maps `unsupported_media_type` to a 415, which is
the entire reason that code is distinct, and renders RFC 9457 problem details as the body.
The body said `"status":422`, because `problemDetailsRender` hard-coded it.

RFC 9457 §3.1 asks that `status` match what the origin server sent, so a stored or
forwarded document can recover it. A body contradicting the header a client has already
acted on is worse than omitting the member.

Now derived from the issues, earliest failure first: negotiation (415), then size (413),
then whether it parsed at all (400), then what it said (422). Four tests pin it. The
existing test asserted the constant rather than the mapping, which is why nothing failed.

## 2. A CSV could not be decoded by the thing built for decoding CSVs

`RowBatch` takes each column's storage kind from the manifest, so an `Int64` field gets an
integer column. A CSV reader handing over `"1001"` had every cell rejected as the wrong
kind, and the field reported `missing_column (expected int64)`.

The text-parsing half — added 2026-09-10, the whole point of which was CSV — lives in the
generated body and reads `stringColumn`. It never got a chance: the column it needed could
not exist.

**Every test of it used `TextStore`, a hand-written `ColumnarSource` that serves
`stringColumn` directly.** So the feature was covered, the transpose was covered, and the
one path that joins them was not. `docs/ROWS.md` §6 described the combination in a
sentence, and the sentence was wrong.

### Three designs, measured, two refused

| design | fill, 8 columns | verdict |
|---|---|---|
| declared kinds (before) | 32.7 ns/row | — |
| a branch in `append(string:)` letting text claim a numeric column | slower | refused |
| infer kinds from the first cell, always | slower | refused |
| **`inferColumnKinds: true`, opt-in** | **40.9 ns/row** | shipped |

`append(string:)` runs once per cell and is four call sites per row on this arm; the row
path has seven earlier storage designs in this file rejected for less. So the cost is
opt-in, paid by sources whose cells are not the declared kind and by nobody else.

### A methodology note that cost an hour

The first two designs were measured against a baseline built minutes earlier, and the
numbers made no sense — one looked like a 50% regression in code that could not affect the
path. **The machine drifts ~15% between release builds taken minutes apart**, and every
cross-build comparison was inside that drift. Re-measuring the untouched baseline twice,
twenty minutes apart, gave 29.0 and 33.2 ns/row for identical code.

The fix is the arm, not more patience: `rowbatch` now fills the same eight columns **both
ways in one process**, each a min of 5. Two rows of one run are comparable; two runs of one
row are not. That is worth generalising — any A/B here that needs a rebuild between the two
halves is measuring the room as much as the code.


---

# Decoding from rows and columns, removed in full

**2026-09-11.** `ColumnarSource`, `ColumnDecodable`, `RowBatch`, `RowDecoder<T>`, `RowSink`
and `@Schema(sources: true)` are gone, along with the `columnar`, `columndecodable`,
`colfloor`, `pathab` and `rowbatch` arms, the `ForeignSource` target, the Foundation column
oracle, and the `sources` compile-time arm. The measurements they produced are left in this
file below — they were true, and two of the lessons in them are not about columns.

**It was not removed for being slow.** The columnar path was the fastest thing in the
library: 11 ns/row against 72 for a `RawValue` per row, 6.6–7.1× the tree path, and
`encodeRow` at 1.2 ns/row against 60 for building a tree and walking it. It won every
technical argument that `KeyedSource` lost.

It was removed because **nothing depended on it**. Neither haul nor swizzle — the two
consumers it was designed for — referenced Assay at all. The audience for Parquet and Arrow
decoding in Swift is small, the audience that would reach for a validation-first decoder to
do it is smaller, and a decoder that also owns column stores is two libraries wearing one
name.

The price of keeping it, for the record:

| | |
|---|---|
| source | ~1,900 lines across four modules |
| compile time | `sources: true` doubled expansion, 164 ms/type against 80 |
| test surface | four suites, a golden fixture, a differential oracle |
| benchmark surface | five arms, a separate target, two allocation-gate rows |
| documentation | three design docs, three website pages |
| bugs | three of the week's finds were in it: `@Check` and `@Transform` never ran on the batch path, the documented CSV route did not work at all, and `ColumnDecodable` was recorded free when it cost ~3 ns/row |

**What survives is the better answer anyway.** `T.validate(_:)` — 76 ns against a value a
fast reader produced its own way. A specialised reader decodes at its own speed in its own
module, and Assay runs the rules afterwards. That was always the seam; it is now the only
one.

## Two lessons from this work that outlive it

Worth carrying, because neither is about columns.

**A diagnostic path threaded eagerly through a hot loop is invisible to every test**,
because tests assert on the diagnostics and never on what producing them cost. Found three
times in one week: the columnar row loop, haul's report before it, and `JSON.Value.parse`,
which is still here and went 2.1× faster when it was fixed.

**A ratio is only evidence about a difference if the difference is large against the
noise** — and a large cost shared by both sides is noise for that purpose. `ColumnDecodable`
read as free for ten days because both sides of the comparison carried a 38 ns/row
allocation that hid a 3 ns difference. When a fix makes an instrument more sensitive, the
conclusions that predate it are unverified again. Not wrong: unverified.


---

# Doing less, not spending more

**2026-09-13.** The efficiency audit (`docs/AUDIT-2026-09-13-efficiency.md`) moved the
headline arms, and the first question to ask of that is whether speed was bought with
memory. It was not, and `totalalloc` is the instrument that can say so — it counts every
allocate and free exactly, and both decoders retain the same output, so the retained part
cancels and what is left is transient work.

| items | Foundation | Assay before | Assay after |
|---|---|---|---|
| 1 | 25 | 6 | 6 |
| 10 | 94 | 55 | **37** |
| 50 | 378 | 257 | **159** |

38% fewer allocations at fifty items. Live blocks are unchanged at 118.7, which is the
point: every allocation removed was allocated and freed inside the decode, the class the
live-block gate structurally cannot see.

Multi-megabyte throughput went from ~700 MB/s to **~1,050 MB/s** for the same reason — a
large document is mostly arrays of structs, and that body was spending well over half its
time building diagnostics for a document that decodes cleanly.

## The trade that went the wrong way first

Three of the fixes replace a linear scan with a hash. That buys O(n) time with O(n) memory,
which is right only when n is large — and the first version of the YAML merge fix built its
`Set` unconditionally. A config file's mapping has a handful of keys: measured on a
realistic small config with two merge keys, **1,954 ns/parse with the set against 1,481
without**. I had made the common case 24% worse in order to fix the adversarial one.

All three are thresholded now — 16 attributes, 24 merged pairs, 8×8 fields — with the
original allocation-free scan below and the hash above, and both ends measured. A hash is
not free, and a fix measured only against the input it was written for is half a fix.


---

## The arms that did not exist

**2026-09-13.** The audit on 09-12 listed five surfaces with no benchmark arm — property
lists, the XML→`RawValue` projection, unions, `@Inline`, `@Wraps` — and the point was not
that they were slow. It was that nothing would move if they became slow.

The XML projection is the proof. It had no arm, and a profile the next day found it
building the full member list for a **leaf** element and then discarding it: 0.0123 s
against 0.0030 s over 100,000 leaves. A 4× regression had shipped in a step nobody timed.

`swift run -c release AssayBench coverage`. Every number has an owner in the same run —
Foundation where a competitor exists, and otherwise the alternative a developer would
write instead, because a bare ns/op has no reader.

| | number | against |
|---|---|---|
| binary plist, 200 rows | **5.55–6.03×** | `PropertyListDecoder` |
| XML plist, 200 rows | **1.33–1.49×** | `PropertyListDecoder` |
| XML→`RawValue`, 2,000 leaves | **93 µs** on top of 180 µs of parse | the parse alone |
| XML→`RawValue`, 2,000 nested | **165 µs** on top of 344 µs of parse | same |
| tagged union | **1.15–1.20×** | the variant decoded directly |
| `@Inline` | **0.81–0.83×** | the nested `@Schema` it replaces |
| `@Wraps` | **1.99–2.08×** | the plain field plus the rule it is sugar for |

Three of these say something worth reading.

**`@Inline` is faster than the nesting it replaces**, at 0.82×. That is the design claim
holding: one table, one mask, one pass, against a nested type's own dispatch.

**The projection is about half the cost of the parse that feeds it** — on the leaf shape,
93 µs against 180 µs. It is the step every YAML, XML, TOML and plist struct decode goes
through, and it now has a number that would move.

**`@Wraps` costs 2× the plain field plus rule it is sugar for**, and that is the one
number here that a reader should act on. It is not a contradiction of `EXPERIENCE.md` §8,
which claims the two produce *identical issues* and says nothing about cost — but "sugar"
reads as "free" and this one is not. `@Wraps` is sugar over `AssayerBacked`, which is a
runtime plan rather than the monomorphic body `@Schema` emits, so the gap is the design's
and not a defect. On a hot path, spell the field out.

The plist rows are the first numbers property lists have ever had. Binary is where the
work went (a random-access object graph, no text to scan); the XML flavour rides the
XXE-refusing XML parser and lands where that parser lands.


---

## The TOML number path, and the oracle it needed

**2026-09-13.** `scanNumberBody` built a `[UInt8]` accumulator for every decimal literal —
one heap allocation per number — because `1_000` puts the digits out of contiguity. The
first pass of the day declined to touch it and said why: removing the accumulator means
re-implementing the digit grammar, and the 710-case official `toml-test` suite that catches
exactly that could not be run locally.

The suite can be run locally. `TOML_TEST_DIR` wants a clone of `toml-lang/toml-test`, and
with one in place the baseline is 210/210 valid and 501/501 invalid before any change.

So the fast path exists now, and the property that makes it safe is written into it: **it
may only ever DECLINE, never accept something the general path would reject.** It reports
nothing into the sink and returns nil on an underscore, an overflow, a leading zero or a
missing digit, after which the cursor rewinds and the unchanged general path re-derives the
input and produces the diagnostic. The two paths cannot disagree about validity; the worst a
mistake costs is a rewind.

  TOML struct decode   1.96× → **2.41×** over TOMLKit   (8k: 77,182 → 66,918 ns)
  TOML node parse      1.18× → **1.51×** over toml++

Both numbers include the string fast path landed earlier the same day.

**A new oracle, because 710 cases across the whole language is not 710 cases across the
number grammar.** `DiffFuzz toml-numbers` generates ~4,900 documents — every literal in
bare, array and inline-table position — heavy on the boundaries a hand-written scanner gets
wrong: separator placement, leading zeros, `Int64` limits in both directions, every
exponent sign spelling, and the shapes that look numeric and are not. **4,227 agree, 687 are
rejected by both, none disagree.**

It also found something that has nothing to do with the fast path. **toml++ rejects float
literals that overflow to infinity or underflow to zero — `1e309`, `1e-400`, `0.5e-308` —
and Assay accepts them.** Verified pre-existing by reverting the parser change and getting
the identical 276 disagreements. 101 literals are held out of the gate with the count
printed, and the reason recorded rather than filtered:

* It is not a TOML question. Assay's JSON path accepts `1e309` too, and a struct meaning
  different things depending on which format its bytes came from is the one property this
  library refuses to have. Fixing TOML alone would *create* that.
* Subnormals are valid binary64 values; toml++ goes through `strtod` and treats `ERANGE` as
  an error, which is arguably stricter than "floats should be implemented as IEEE 754
  binary64".
* The overflow half is the weaker of the two — a finite literal becoming `inf` is a number
  read as a different number, which this codebase refuses elsewhere.

**Closed the same day, on every format.** `1e309` and `1e-400` are refused now: JSON and
TOML report `number_overflow`, YAML leaves the scalar unresolved so the schema says `must be
a number, found "1e309"`. Foundation's `JSONDecoder` throws on both and toml++ rejects both,
so this moved Assay from outlier to majority. The JSON check sits in `slowDouble`, which is
`@inline(never)` and reachable only by subnormals, >19 significant digits and huge exponents
— the integer-shaped and Clinger paths are bounded by construction and cannot overflow — so
the hot path is untouched, and the falsification arm confirms it at 6.00× (float-dense
8.27×), inside its usual spread.

What is left is 26 SUBNORMAL literals, and that one is unsettled rather than wrong. Measured:
toml++ accepts `2.2250738585072014e-308` (the least positive *normal*) and rejects every
subnormal, `5e-324` included, via `std::from_chars` returning `result_out_of_range` — which
it reports as "not representable in 64 bits", though a subnormal plainly is. **TOML 1.0.0
requires an error for an integer that cannot be represented losslessly, in those words, and
says nothing equivalent about floats**; the float section is the single sentence "Floats
should be implemented as IEEE 754 binary64 values", and the official suite's largest
exponent is `3e2`. With no arbiter, both readings stand: a subnormal is a binary64 value
(Assay, and Foundation), or subnormals are lossy and lossy is an error (toml++). Assay takes
the first, because the second does not generalise — `0.1` is lossy too. Held-out list: 26,
down from 101.


---

## A profiling matrix: one property per fixture, one verb per task

**2026-09-13.** Every arm in `AssayBench` grew one at a time, each against one corpus shape,
so a number told you how fast that shape was and nothing about why. The corpus cannot answer
"why" even in principle: `apimodel` differs from `short-strings` in field count, key length,
value type, nesting and value width all at once, so when two shapes disagree there is
nothing to attribute it to.

Two of this week's findings were luck rather than method. The XML→`RawValue` projection had
regressed **4×** and nothing timed that step. `@Wraps` costs **2×** the plain field it is
sugar for, and that surfaced only when an arm was finally written for it. `AssayMatrix`
makes the method the method.

    swift run -c release AssayMatrix run [--baseline f.json] [--save f.json] [--gate]
    swift run -c release AssayMatrix run --shapes base,fields-20 --only struct,value

Eighteen fixtures, each moving exactly ONE property off a base of five fields, short keys,
short string values, flat, minified, no nulls, all valid. Seven verbs. Every cell runs in its
own process — that keeps allocator state and page cache from leaking between measurements and
is the only way to attribute peak memory — with time taking the best of nine 100 ms reps and
memory the worst.

### What it is not

**It does not gate CI, and must not.** `CLAUDE.md`'s honesty rules say to gate on allocation
counts with absolute thresholds and never on wall clock, and a hosted runner has no business
deciding a 20% question. Five runs of the unchanged matrix on this machine spread by a median
of 3.4%, a p90 of 8.0% and a worst case of 15%. So 5% is worth PRINTING — a human can tell a
real move from a jittery cell by looking at whether the shape's other verbs moved too — and
the `--gate` threshold is 20%, above everything the noise produced. It is a wide net for
structural surprises, not an instrument for resolving 5%; that is what the individual arms
are for, with a named competitor beside each number.

**The detector is verified in both directions.** Forcing every JSON string through the escape
slow path turns the table red — `base/struct` +431%, 60 cells past the gate, exit 1 — and
reverting it returns the gate to silence against three separate baselines. More usefully, the
injection did *not* move `values-int`, `values-bool`, `values-double` or `optional-absent`,
and moved `escapes-100` by only 7% because that fixture was already on the slow path. The
table says **where**, which is the entire claim.

### What the first run found

| axis | measured |
|---|---|
| escape density, value width held equal | `escapes-0` 74.5 → `escapes-100` **403.0 ns/element, 5.4×** |
| value type, five fields each | bool 36.1 · int 44.5 · double 52.7 · string 63.2 · **Date 190.8** |
| pretty-printed input | **+7%** over minified |
| error density (`diagnose`) | clean 65.2 · 1% 65.0 · 10% 75.6 · **100% 177.6 (2.7×)** |
| verbs on the base shape | `diagnose` 1.03× `struct` · `validate` 0.85× · `raw` 0.86× · `encode` 1.89× · `value` **3.21×** |

Three of these were not known before. The escape fork is the largest single multiplier in
the table and had a corpus shape but never a gradient. `Date` at 3× a string field is the
price of the hand-written parser, now per element. And **`+7%` for pretty-printed input
confirms the efficiency audit's estimate of ~8% for a whitespace skipper** — a prediction
made in August and never checked, which turns out to have been right and to describe an
opportunity too small to take.

### What the anomalies turned out to be

The first run reported two: per-field decode cost that was not monotonic in field count, and
an unknown-key skip that seemed to save less as more fields were skipped. Both were one
question, and the answer was better than either.

**They were the same number.** Modelling a skipped field as a constant cost and a decoded
field as a per-shape cost fits the two `skip` cells to 0.1%: skipping is a flat **6.7 ns per
field** and it is *decoding* that varied. So there was one question — why did a field cost
14.8 ns at twenty fields and 9.2 at a hundred?

**Because the hundred-field row was not decoding a hundred fields.** `@Schema` accepts at
most 64, so the matrix's own shape/type dispatch fell through to the 20-field type and
measured twenty decoded fields plus eighty structurally skipped ones. The model predicts that
cell at 835 ns against 918 measured. The row was removed, and the field-count axis moved to
`AssayBench fieldsweep` where key width is held constant and every count is inside the real
ceiling. A harness that measures the wrong thing is worse than no harness, and this one did
it within a day of being built — which is the argument for checking a surprising number
before believing it, not the argument against the tool.

### The field-count sweep, and the thing it found

`swift run -c release AssayBench fieldsweep`. Keys are three bytes throughout and values one,
so ns/field is the cost of FINDING a field rather than reading it.

| fields | ns/field | | fields | ns/field |
|---|---|---|---|---|
| 2 | 16.86 | | 14 | 15.22 |
| 4 | 15.62 | | 16 | 15.45 |
| 6 | 14.27 | | 20 | 15.90 |
| 8 | 14.36 | | 24 | 17.42 |
| 9 | **14.25** | | 32 | 18.25 |
| 10 | **15.14** | | 48 | 20.32 |
| 11 | 14.07 | | 64 | **22.87** |
| 12 | 14.52 | | | |

**There is no discontinuity at ten fields.** Experiment #1 established by reading assembly
that a switch over a `UInt8` candidate index becomes a real arm64 jump table at N ≥ 10 and a
balanced search tree below; 9 → 10 costs **+6%**, inside the general drift. The table exists
and it does not announce itself.

What the curve does instead is **rise by 60% from nine fields to sixty-four**, and that has a
cause worth the whole exercise:

> **The window dispatch stops working between 11 and 13 fields.** After that, every field
> lookup is a linear chain of `keyMatches` calls.

`WindowSearch` looks for a single 8-bit window — one `(byteOffset, shift)` pair — whose value
is DISTINCT across every key. That is a birthday bound: with more keys competing for 256
slots a collision becomes near-certain, and for keys sharing a prefix, sooner. Measured by
expanding the macro and reading which dispatch it emitted:

| fields | `k00…` (same length, same prefix) | realistic names |
|---|---|---|
| ≤ 10 | window | window |
| 11–12 | **linear** | window |
| ≥ 13 | **linear** | **linear** |

The fallback buckets by byte length and then compares linearly inside the bucket. That is
better than `switch` over a `String` — rule 1's hazard — because `keyMatches` is a byte
compare and length bucketing is free. It is still O(bucket) per key on a path whose entire
design is O(1), and it is undocumented: `CLAUDE.md` presents window dispatch as *the* design
without saying it has a ceiling of about a dozen fields.

**The fix is sized and it is small.** Give each length bucket its own window search instead of
a linear chain. Buckets are small because real key names vary in length, and a window that
cannot separate twenty-four keys separates seven easily. Checked statically against a
realistic key set: at 13, 16, 20 and 24 fields the global search fails every time, and a
per-bucket search succeeds for **every bucket**, the largest holding seven keys.

### Per-bucket windows, built — and a correction to the paragraph above (2026-09-19)

Built as sized: every length bucket of three or more keys now gets its own window
(`WindowSearch.bucketSearch`), and what stays linear is a collision group inside a bucket.
The search takes the window whose LARGEST collision group is smallest rather than insisting on
a perfect one, because `k00`…`k63` have no perfect window at all — they differ in two decimal
digits whose useful bits are not contiguous — and a chain of seven beats a chain of sixty-four.
The hazard a window adds is a false accept (an undeclared key of the same length landing on a
declared arm); `keyMatches` inside the arm still refuses it, and `BucketDispatchTests` throws
every one-byte mutation of every declared key — 2,000+ — at a `.reject` schema to prove it.

Old and new builds run alternately, three times each, minimum reported:

| fields | `k00…` before | after | | realistic names | before | after |
|---|---|---|---|---|---|---|
| 12 | 168.6 | 158.9 (−5.8%) | | 12 | 181.3 | 185.9 (+2.5%) |
| 16 | 245.8 | 220.2 (**−10.4%**) | | 13 | 188.2 | 192.6 (+2.3%) |
| 24 | 400.3 | 336.1 (**−16.0%**) | | 16 | 242.4 | 237.4 (−2.1%) |
| 32 | 564.5 | 463.5 (**−17.9%**) | | 24 | 356.5 | 364.9 (+2.4%) |
| 48 | 960.7 | 760.4 (**−20.8%**) | | 32 | 487.5 | 508.9 (+4.4%) |
| 64 | 1446.3 | 1048.1 (**−27.5%**) | | 48 | 813.1 | 820.6 (+0.9%) |

ns per element. The realistic 12-field row still uses the GLOBAL window — its generated code
did not change — and it moved +2.5%, which is the noise floor for this column.

**The correction.** The section above says the curve "rises 60% from nine fields to
sixty-four" because the fallback is linear, and implies that is a property of wide structs.
It is a property of **same-length, same-prefix keys**. On realistic names — lengths 2 to 12,
first bytes mostly distinct — ns/field is flat at ~15 from 12 to 48 fields both before and
after this change, because a failed `keyMatches` exits on the first byte and a bucket holds
at most nine keys. `k00…` pays two to three byte compares per failed candidate across a
64-long chain, which is where the 60% came from. So the change is a large win for key sets
that look like `k00…` (generated schemas, `field_1…field_n`, column-style names) and neutral
on the shape most APIs have.

**And "neutral" was only true at run time.** The compile-time gate's own key set at 24 fields
(realistic names, four buckets of 3-7 keys) measured **+12.7%** — 16.31 s against 18.38 s for
100 types, minimum of five builds alternated old/new, every pair in the same direction: about
20 ms per type for four inner switches that bought nothing. So the window is now emitted only
where the chain is EXPENSIVE. `WindowSearch.chainCost` computes, at expansion, the bytes a
linear chain compares on average — each earlier candidate costs its common prefix with the
target plus one — and a bucket gets a window at 8 or more. The two populations do not overlap:
every bucket of the 48-name realistic set scores 1.0-4.2, `k00…` scores 14.8 at twelve keys and
67 at sixty-four. Realistic names therefore emit exactly the code they emitted before this
change; `created_at/created_by/created_on`-style prefix families and generated names get the
window, and the win above.

### The two anomalies as first reported, kept for the record

**Per-field cost is not monotonic in field count.**

| fields | ns/element | ns/field |
|---|---|---|
| 2 | 28.1 | 14.05 |
| 5 | 63.2 | 12.64 |
| 20 | 296.1 | **14.81** |
| 100 | 918.4 | **9.18** |

Twenty fields is the worst point per field — worse than five and much worse than a hundred.
Experiment #1 found that a switch over a `UInt8` candidate index becomes a real arm64 jump
table at N ≥ 10 and a balanced search tree below it, so twenty fields is the *first* shape in
this repository that has ever exercised the table a benchmark, and it is not faster per field
for it. The axis is not perfectly controlled — `f10`…`f99` are three bytes where `f0`…`f9`
are two, and per-element overhead amortises differently — so this is a question, not a
verdict. It is the question nobody could have asked before, because no benchmark here had
more than nine fields.

**The unknown-key skip does not scale the way it should.**

| shape | struct | skip (2 fields declared) | saved |
|---|---|---|---|
| base (5) | 63.2 | 45.5 | 28% |
| fields-20 | 296.1 | 140.0 | 53% |
| fields-100 | 918.4 | 678.4 | **26%** |

Skipping 98 of 100 fields saves less than skipping 18 of 20. Some of this is real — the key
still has to be scanned and matched whether or not the value is wanted — but the shape of the
curve is wrong for a path whose whole purpose is to make undeclared fields cheap, and it is
listed in `CLAUDE.md` build order phase 2 as one of "the unclaimed wins".

Both are recorded here rather than chased, because the matrix's job today was to exist and to
be trustworthy. Neither would have been visible without it.

---

# Exact counts: instructions, ARC traffic and heap per call (2026-09-19)

`Benchmarks/count.sh` (a container on a Mac) or `python3 Benchmarks/count.py run` (Linux).
Every profiling-matrix cell runs under Valgrind at K=1 and K=3 calls of its verb, and the
difference is halved, so start-up and one-time statics cancel and what remains is one steady-
state call. Valgrind counts in software and needs no PMU, which is why this runs on a hosted
runner where package-benchmark's `.instructions` reports zero.

**Determinism**, measured before anything was built on it: three runs of one binary gave
IDENTICAL runtime call counts and instruction counts within ~50 of 4.9 million. Calls are
therefore gated exactly and instructions with a 2% tolerance. `.github/workflows/efficiency.yml`
gates x86-64 and aarch64; the aarch64 baseline is `Benchmarks/counts-baseline.aarch64.json`
(Swift 6.3.3), and x86-64's comes from the first CI run.

**Verified in both directions.** Declaring `String(unsafeUninitializedCapacity:)` 16 bytes
larger than the byte count (the trap `Strings.swift`'s header warns about) failed `base/struct`
(+10,000 blocks, +146% instructions) and `base/skip`, and left `values-int/struct`, which has
no strings, untouched. Reverting: "No counter moved."

A selection, per call on 2,000 elements:

| cell | Ir/element | String releases | String retains | uniqueness checks | heap blocks |
|---|---:|---:|---:|---:|---:|
| base/struct (5 String fields) | 2,376 | 20,002 | 1 | 4,000 | 14 |
| values-int/struct | 1,746 | 2 | 1 | 4,000 | 14 |
| values-long/struct | 8,004 | 14,002 | 1 | 4,000 | 10,014 |
| base/validate | 2,190 | 30,000 | 30,000 | 2,000 | 1 |
| base/encode | 4,325 | 32,001 | 32,001 | 106,011 | 2,009 |
| base/value (`JSON.Value`) | 5,898 | 30,002 | 10,001 | 36,003 | 8,016 |

What the first run found, each now a row in `docs/EFFICIENCY.md`'s ledger:

- **Two String releases per decoded field, and only one is the caller's.** 10,000 are
  the benchmark destroying its result. The other 10,000 are inside `AssayReader.scanString()`,
  and only on the small-string path: forcing strings to the heap removed them.
- **`validate` does three retain/release pairs per String field** while allocating one block.
- **`encode` checks buffer uniqueness 53 times per element**; decode checks 2.
- **The top-level array reallocates about 12 times** at 2,000 elements (14 blocks where
  the floor is about 2).

**A caution on reading it.** The first run double-counted: `swift_bridgeObjectRelease` calls
`swift_release` internally, and so does `swift_slowAlloc` → `malloc`. Counting both made it
four releases per field. `count.py` now ignores calls whose caller is the runtime itself.

Also found: **`AssayMatrix` had never compiled on Linux.** Glibc's `stdout` is a mutable global
that Swift 6 mode rejects, and `RUSAGE_SELF` imports as an enum there. Nothing had built it
off a Mac until this needed to.

## Scaling: is every verb linear? (2026-09-19)

`Benchmarks/count.sh scale` (or `count.py scale` on Linux). Nine axes, each sweeping ONE
property over four sizes with everything else held still, and the log-log slope of per-call
instructions and heap bytes over them. The gate is the TAIL slope (last two sizes) at 1.10:
that admits linear cost plus a shrinking constant, and refuses n log n at these sizes (tail
≈1.14) as well as anything quadratic. It is absolute, so it needs no baseline.

**All 28 series are linear** on aarch64 Linux. Instruction tail slopes run 0.69–1.07, and the
steepest is `depth/value` at 1.07. Heap bytes are no steeper than instructions anywhere. The
escaped-length heap slope is suspiciously flat at 0.05, and that is ledger row 6, not a
finding.

**Verified in both directions.** Inserting object members at the front instead of appending
(a textbook quadratic) failed exactly `object-width/value` at 1.85, while `elements/value`
and `object-width/raw` (whose tree is built in setup) stayed at 1.00. Reverting restored 1.02.

The portable half is `Tests/AssayTests/ScalingTests.swift`: the same question as a
wall-clock RATIO inside one process (8× input must cost < 16×, best-of-five interleaved), for
JSON, YAML, XML and TOML, on every platform the suite runs, Windows included. It found a
parser bug on its first run, unrelated to cost: YAML indentless block sequences (`items:\n- a`)
are refused, and one form is silently mis-parsed. That is recorded in `ROADMAP.md` and pinned
with `withKnownIssue`.
